<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/Pandas_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Pandas function

| Function        | Easy Definition                    |
| --------------- | ---------------------------------- |
| `df.head()`     | Starting ki rows                   |
| `df.tail()`     | Last ki rows                       |
| `df.info()`     | Data ki complete basic information |
| `df.describe()` | Numerical statistics               |
| `df.shape`      | Rows aur columns ki number         |
| `df.columns`    | Column names                       |
| `df.index`      | Index information                  |
| `df.dtypes`     | Data types                         |

Pandas Most Important Functions


pd.Series()

pd.DataFrame()

pd.read_csv()

df.to_csv()

df.head()

df.tail()

df.info()

df.describe()

df.shape

df.columns

df.dtypes

df.loc[]

df.iloc[]

df.insert()

df.drop()

df.isnull()

df.dropna()

df.fillna()

df.duplicated()

df.drop_duplicates()

df.rename()

df.replace()

df.astype()

df.sort_values()

df.unique()

df.nunique()

df.value_counts()

df.groupby()

df.query()

df.sum()

df.mean()

df.median()

df.mode()

df.min()

df.max()

df.count()

df.std()

df.var()

pd.concat()

pd.merge()

df.join()

In [ ]:
import pandas as pd

csv_1 = pd.read_csv("/content/Company_Employee_Data_Analysis.csv")
csv_1

,Employee_ID,Name,Age,Gender,Department,Experience_Years,Salary,City,Performance_Score,Joining_Date
0,10001,Aarav Sharma,25,Female,IT,11,82061,Indore,3,2017-06-29
1,10002,Priya Sharma,26,Male,HR,4,56836,Bhopal,5,2013-12-13
2,10003,Rahul Sharma,35,Female,Finance,10,75650,Pune,1,2014-02-06
3,10004,Anjali Sharma,29,Male,Sales,4,65136,Mumbai,5,2012-08-05
4,10005,Aman Sharma,28,Female,Marketing,9,78694,Delhi,5,2021-05-29
...,...,...,...,...,...,...,...,...,...,...
95,10096,Nisha Singh,28,Male,Operations,11,73476,Jaipur,3,2018-04-01
96,10097,Varun Singh,24,Female,IT,14,93994,Indore,3,2023-06-05
97,10098,Simran Singh,43,Male,HR,7,68186,Bhopal,3,2012-08-14
98,10099,Deepak Singh,30,Female,Finance,2,63730,Pune,5,2017-12-14
99,10100,Meena Singh,25,Male,Sales,1,57721,Mumbai,4,2019-10-02

In [ ]:
csv_1.index

RangeIndex(start=0, stop=100, step=1)

In [ ]:
csv_1.columns

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'Department',
       'Experience_Years', 'Salary', 'City', 'Performance_Score',
       'Joining_Date'],
      dtype='object')

In [ ]:
csv_1.describe()

,Employee_ID,Age,Experience_Years,Salary,Performance_Score
count,100.000000,100.000000,100.000000,100.000000,100.000000
mean,10050.500000,31.870000,7.110000,70795.700000,3.050000
std,29.011492,6.804121,4.167927,11535.048479,1.445124
min,10001.000000,22.000000,1.000000,51280.000000,1.000000
25%,10025.750000,26.000000,4.000000,61411.750000,2.000000
50%,10050.500000,30.000000,7.000000,70503.000000,3.000000
75%,10075.250000,36.250000,11.000000,78691.000000,4.000000
max,10100.000000,45.000000,15.000000,103077.000000,5.000000

In [ ]:
csv_1.head()

,Employee_ID,Name,Age,Gender,Department,Experience_Years,Salary,City,Performance_Score,Joining_Date
0,10001,Aarav Sharma,25,Female,IT,11,82061,Indore,3,2017-06-29
1,10002,Priya Sharma,26,Male,HR,4,56836,Bhopal,5,2013-12-13
2,10003,Rahul Sharma,35,Female,Finance,10,75650,Pune,1,2014-02-06
3,10004,Anjali Sharma,29,Male,Sales,4,65136,Mumbai,5,2012-08-05
4,10005,Aman Sharma,28,Female,Marketing,9,78694,Delhi,5,2021-05-29

In [ ]:
csv_1.head(4)

,Employee_ID,Name,Age,Gender,Department,Experience_Years,Salary,City,Performance_Score,Joining_Date
0,10001,Aarav Sharma,25,Female,IT,11,82061,Indore,3,2017-06-29
1,10002,Priya Sharma,26,Male,HR,4,56836,Bhopal,5,2013-12-13
2,10003,Rahul Sharma,35,Female,Finance,10,75650,Pune,1,2014-02-06
3,10004,Anjali Sharma,29,Male,Sales,4,65136,Mumbai,5,2012-08-05

In [ ]:
csv_1.tail()

,Employee_ID,Name,Age,Gender,Department,Experience_Years,Salary,City,Performance_Score,Joining_Date
95,10096,Nisha Singh,28,Male,Operations,11,73476,Jaipur,3,2018-04-01
96,10097,Varun Singh,24,Female,IT,14,93994,Indore,3,2023-06-05
97,10098,Simran Singh,43,Male,HR,7,68186,Bhopal,3,2012-08-14
98,10099,Deepak Singh,30,Female,Finance,2,63730,Pune,5,2017-12-14
99,10100,Meena Singh,25,Male,Sales,1,57721,Mumbai,4,2019-10-02

In [ ]:
csv_1.tail(3)

,Employee_ID,Name,Age,Gender,Department,Experience_Years,Salary,City,Performance_Score,Joining_Date
97,10098,Simran Singh,43,Male,HR,7,68186,Bhopal,3,2012-08-14
98,10099,Deepak Singh,30,Female,Finance,2,63730,Pune,5,2017-12-14
99,10100,Meena Singh,25,Male,Sales,1,57721,Mumbai,4,2019-10-02

In [ ]:
csv_1['Experience_Years']

0     11
1      4
2     10
3      4
4      9
      ..
95    11
96    14
97     7
98     2
99     1
Name: Experience_Years, Length: 100, dtype: int64

In [ ]:
csv_1[:2]

,Employee_ID,Name,Age,Gender,Department,Experience_Years,Salary,City,Performance_Score,Joining_Date
0,10001,Aarav Sharma,25,Female,IT,11,82061,Indore,3,2017-06-29
1,10002,Priya Sharma,26,Male,HR,4,56836,Bhopal,5,2013-12-13

In [ ]:
csv_1[6:11]

,Employee_ID,Name,Age,Gender,Department,Experience_Years,Salary,City,Performance_Score,Joining_Date
6,10007,Rohit Sharma,27,Female,IT,13,103077,Hyderabad,4,2019-08-19
7,10008,Sneha Sharma,26,Male,HR,5,59700,Jaipur,3,2014-04-17
8,10009,Vikas Sharma,34,Female,Finance,2,63396,Indore,3,2019-09-18
9,10010,Pooja Sharma,30,Male,Sales,10,70880,Bhopal,4,2024-01-10
10,10011,Arjun Sharma,34,Female,Marketing,2,55322,Pune,5,2018-07-29

In [ ]:
print(type(csv_1))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
csv_1.index.array

<NumpyExtensionArray>
[ np.int64(0),  np.int64(1),  np.int64(2),  np.int64(3),  np.int64(4),
  np.int64(5),  np.int64(6),  np.int64(7),  np.int64(8),  np.int64(9),
 np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14),
 np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19),
 np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24),
 np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29),
 np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34),
 np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39),
 np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44),
 np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49),
 np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54),
 np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59),
 np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64),
 np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(69),
 np.int64(70), np.int64(71), np.int64(72), np.int64(73), np.int64(74),
 np.int64(75), np.int64(76), np.int64(77), np.int64(78), np.int64(79),
 np.int64(80), np.int64(81), np.int64(82), np.int64(83), np.int64(84),
 np.int64(85), np.int64(86), np.int64(87), np.int64(88), np.int64(89),
 np.int64(90), np.int64(91), np.int64(92), np.int64(93), np.int64(94),
 np.int64(95), np.int64(96), np.int64(97), np.int64(98), np.int64(99)]
Length: 100, dtype: int64

In [ ]:
csv_1.to_numpy()

array([[10001, 'Aarav Sharma', 25, 'Female', 'IT', 11, 82061, 'Indore',
        3, '2017-06-29'],
       [10002, 'Priya Sharma', 26, 'Male', 'HR', 4, 56836, 'Bhopal', 5,
        '2013-12-13'],
       [10003, 'Rahul Sharma', 35, 'Female', 'Finance', 10, 75650,
        'Pune', 1, '2014-02-06'],
       [10004, 'Anjali Sharma', 29, 'Male', 'Sales', 4, 65136, 'Mumbai',
        5, '2012-08-05'],
       [10005, 'Aman Sharma', 28, 'Female', 'Marketing', 9, 78694,
        'Delhi', 5, '2021-05-29'],
       [10006, 'Neha Sharma', 36, 'Male', 'Operations', 4, 58824,
        'Bengaluru', 3, '2012-02-23'],
       [10007, 'Rohit Sharma', 27, 'Female', 'IT', 13, 103077,
        'Hyderabad', 4, '2019-08-19'],
       [10008, 'Sneha Sharma', 26, 'Male', 'HR', 5, 59700, 'Jaipur', 3,
        '2014-04-17'],
       [10009, 'Vikas Sharma', 34, 'Female', 'Finance', 2, 63396,
        'Indore', 3, '2019-09-18'],
       [10010, 'Pooja Sharma', 30, 'Male', 'Sales', 10, 70880, 'Bhopal',
        4, '2024-01-10'],
       [10011, 'Arjun Sharma', 34, 'Female', 'Marketing', 2, 55322,
        'Pune', 5, '2018-07-29'],
       [10012, 'Kavya Sharma', 42, 'Male', 'Operations', 14, 86724,
        'Mumbai', 3, '2024-12-12'],
       [10013, 'Amit Sharma', 44, 'Female', 'IT', 4, 71568, 'Delhi', 1,
        '2017-02-09'],
       [10014, 'Riya Sharma', 31, 'Male', 'HR', 13, 71619, 'Bengaluru',
        2, '2014-04-07'],
       [10015, 'Karan Sharma', 30, 'Female', 'Finance', 7, 76996,
        'Hyderabad', 3, '2015-08-25'],
       [10016, 'Nisha Sharma', 33, 'Male', 'Sales', 6, 66574, 'Jaipur',
        3, '2013-08-07'],
       [10017, 'Varun Sharma', 42, 'Female', 'Marketing', 10, 70500,
        'Indore', 5, '2017-06-28'],
       [10018, 'Simran Sharma', 36, 'Male', 'Operations', 3, 54831,
        'Bhopal', 3, '2024-06-28'],
       [10019, 'Deepak Sharma', 43, 'Female', 'IT', 4, 73656, 'Pune', 1,
        '2017-02-19'],
       [10020, 'Meena Sharma', 23, 'Male', 'HR', 14, 80044, 'Mumbai', 4,
        '2018-01-02'],
       [10021, 'Aarav Patel', 28, 'Female', 'Finance', 2, 65322, 'Delhi',
        3, '2016-10-07'],
       [10022, 'Priya Patel', 37, 'Male', 'Sales', 11, 80410,
        'Bengaluru', 4, '2015-03-16'],
       [10023, 'Rahul Patel', 26, 'Female', 'Marketing', 5, 62025,
        'Hyderabad', 5, '2024-02-02'],
       [10024, 'Anjali Patel', 45, 'Male', 'Operations', 5, 61485,
        'Jaipur', 4, '2025-02-01'],
       [10025, 'Aman Patel', 33, 'Female', 'IT', 7, 78643, 'Indore', 2,
        '2023-06-06'],
       [10026, 'Neha Patel', 24, 'Male', 'HR', 8, 62768, 'Bhopal', 1,
        '2015-06-06'],
       [10027, 'Rohit Patel', 27, 'Female', 'Finance', 11, 91823, 'Pune',
        4, '2025-05-17'],
       [10028, 'Sneha Patel', 34, 'Male', 'Sales', 2, 59562, 'Mumbai', 5,
        '2022-07-01'],
       [10029, 'Vikas Patel', 30, 'Female', 'Marketing', 9, 75697,
        'Delhi', 1, '2014-07-27'],
       [10030, 'Pooja Patel', 39, 'Male', 'Operations', 11, 70506,
        'Bengaluru', 3, '2014-07-02'],
       [10031, 'Arjun Patel', 35, 'Female', 'IT', 5, 74115, 'Hyderabad',
        4, '2012-01-27'],
       [10032, 'Kavya Patel', 45, 'Male', 'HR', 12, 74468, 'Jaipur', 5,
        '2016-01-03'],
       [10033, 'Amit Patel', 25, 'Female', 'Finance', 9, 85020, 'Indore',
        3, '2023-05-21'],
       [10034, 'Riya Patel', 28, 'Male', 'Sales', 10, 73130, 'Bhopal', 3,
        '2015-08-16'],
       [10035, 'Karan Patel', 38, 'Female', 'Marketing', 9, 65509,
        'Pune', 5, '2019-04-09'],
       [10036, 'Nisha Patel', 22, 'Male', 'Operations', 8, 61832,
        'Mumbai', 3, '2018-11-24'],
       [10037, 'Varun Patel', 23, 'Female', 'IT', 4, 72972, 'Delhi', 5,
        '2013-10-07'],
       [10038, 'Simran Patel', 45, 'Male', 'HR', 2, 54990, 'Bengaluru',
        1, '2023-12-12'],
       [10039, 'Deepak Patel', 26, 'Female', 'Finance', 13, 82906,
        'Hyderabad', 4, '2024-04-30'],
       [10040, 'Meena Patel', 30, 'Male', 'Sales', 3, 62740, 'Jaipur', 5,
        '2021-06-28'],
       [10041, 'Aarav Verma', 39, 'Female', 'Marketing', 4, 63976,
        'Indore', 2, '2018-12-28'],
       [10042, 'Priya Verma', 43, 'Male', 'Operations', 7, 67810,
        'Bhopal', 3, '2021-10-28'],
       [10043, 'Rahul Verma', 38, 'Female', 'IT', 15, 101360, 'Pune', 1,
        '2017-07-23'],
       [10044, 'Anjali Verma', 24, 'Male', 'HR', 4, 58768, 'Mumbai', 1,
        '2025-03-12'],
       [10045, 'Aman Verma', 29, 'Female', 'Finance', 9, 84345, 'Delhi',
        2, '2012-02-28'],
       [10046, 'Neha Verma', 44, 'Male', 'Sales', 2, 60584, 'Bengaluru',
        1, '2017-02-18'],
       [10047, 'Rohit Verma', 23, 'Female', 'Marketing', 2, 56352,
        'Hyderabad', 1, '2023-07-13'],
       [10048, 'Sneha Verma', 30, 'Male', 'Operations', 4, 59480,
        'Jaipur', 4, '2016-10-21'],
       [10049, 'Vikas Verma', 26, 'Female', 'IT', 9, 91829, 'Indore', 5,
        '2024-12-03'],
       [10050, 'Pooja Verma', 29, 'Male', 'HR', 8, 69744, 'Bhopal', 4,
        '2016-04-08'],
       [10051, 'Arjun Verma', 25, 'Female', 'Finance', 2, 65698, 'Pune',
        4, '2019-12-12'],
       [10052, 'Kavya Verma', 35, 'Male', 'Sales', 7, 72192, 'Mumbai', 1,
        '2014-03-17'],
       [10053, 'Amit Verma', 34, 'Female', 'Marketing', 1, 54991,
        'Delhi', 3, '2014-06-14'],
       [10054, 'Riya Verma', 28, 'Male', 'Operations', 4, 55556,
        'Bengaluru', 5, '2022-01-23'],
       [10055, 'Karan Verma', 35, 'Female', 'IT', 3, 70625, 'Hyderabad',
        3, '2022-05-17'],
       [10056, 'Nisha Verma', 24, 'Male', 'HR', 4, 59628, 'Jaipur', 5,
        '2014-03-13'],
       [10057, 'Varun Verma', 42, 'Female', 'Finance', 1, 62607,
        'Indore', 1, '2014-02-03'],
       [10058, 'Simran Verma', 29, 'Male', 'Sales', 15, 82600, 'Bhopal',
        4, '2022-11-22'],
       [10059, 'Deepak Verma', 28, 'Female', 'Marketing', 8, 70568,
        'Pune', 1, '2015-09-10'],
       [10060, 'Meena Verma', 22, 'Male', 'Operations', 7, 64093,
        'Mumbai', 3, '2022-03-16'],
       [10061, 'Aarav Gupta', 35, 'Female', 'IT', 5, 79630, 'Delhi', 5,
        '2022-11-30'],
       [10062, 'Priya Gupta', 28, 'Male', 'HR', 3, 56321, 'Bengaluru', 2,
        '2013-04-24'],
       [10063, 'Rahul Gupta', 45, 'Female', 'Finance', 10, 86100,
        'Hyderabad', 1, '2019-01-13'],
       [10064, 'Anjali Gupta', 23, 'Male', 'Sales', 1, 57696, 'Jaipur',
        4, '2023-04-12'],
       [10065, 'Aman Gupta', 38, 'Female', 'Marketing', 15, 79330,
        'Indore', 1, '2023-05-23'],
       [10066, 'Neha Gupta', 27, 'Male', 'Operations', 2, 51280,
        'Bhopal', 5, '2013-07-10'],
       [10067, 'Rohit Gupta', 29, 'Female', 'IT', 11, 90586, 'Pune', 1,
        '2024-10-10'],
       [10068, 'Sneha Gupta', 40, 'Male', 'HR', 4, 60868, 'Mumbai', 1,
        '2013-11-02'],
       [10069, 'Vikas Gupta', 43, 'Female', 'Finance', 7, 78865, 'Delhi',
        5, '2023-09-22'],
       [10070, 'Pooja Gupta', 30, 'Male', 'Sales', 6, 66508, 'Bengaluru',
        3, '2017-05-09'],
       [10071, 'Arjun Gupta', 34, 'Female', 'Marketing', 5, 60840,
        'Hyderabad', 3, '2022-04-03'],
       [10072, 'Kavya Gupta', 24, 'Male', 'Operations', 6, 57114,
        'Jaipur', 4, '2024-08-17'],
       [10073, 'Amit Gupta', 24, 'Female', 'IT', 2, 70202, 'Indore', 2,
        '2023-05-07'],
       [10074, 'Riya Gupta', 26, 'Male', 'HR', 5, 61070, 'Bhopal', 1,
        '2017-06-24'],
       [10075, 'Karan Gupta', 31, 'Female', 'Finance', 6, 70938, 'Pune',
        4, '2024-03-08'],
       [10076, 'Nisha Gupta', 31, 'Male', 'Sales', 12, 88024, 'Mumbai',
        5, '2012-03-05'],
       [10077, 'Varun Gupta', 39, 'Female', 'Marketing', 11, 75243,
        'Delhi', 1, '2015-01-05'],
       [10078, 'Simran Gupta', 25, 'Male', 'Operations', 5, 56595,
        'Bengaluru', 5, '2015-06-27'],
       [10079, 'Deepak Gupta', 31, 'Female', 'IT', 5, 78690, 'Hyderabad',
        2, '2019-09-09'],
       [10080, 'Meena Gupta', 43, 'Male', 'HR', 4, 61192, 'Jaipur', 3,
        '2023-05-03'],
       [10081, 'Aarav Singh', 30, 'Female', 'Finance', 8, 72832,
        'Indore', 1, '2021-07-01'],
       [10082, 'Priya Singh', 30, 'Male', 'Sales', 14, 77260, 'Bhopal',
        1, '2019-06-25'],
       [10083, 'Rahul Singh', 26, 'Female', 'Marketing', 13, 88452,
        'Pune', 3, '2015-08-16'],
       [10084, 'Anjali Singh', 36, 'Male', 'Operations', 12, 79548,
        'Mumbai', 4, '2024-07-30'],
       [10085, 'Aman Singh', 25, 'Female', 'IT', 1, 66654, 'Delhi', 2,
        '2024-03-27'],
       [10086, 'Neha Singh', 33, 'Male', 'HR', 1, 52692, 'Bengaluru', 5,
        '2015-04-28'],
       [10087, 'Rohit Singh', 26, 'Female', 'Finance', 7, 71095,
        'Hyderabad', 3, '2020-03-06'],
       [10088, 'Sneha Singh', 23, 'Male', 'Sales', 15, 88480, 'Jaipur',
        2, '2017-08-06'],
       [10089, 'Vikas Singh', 25, 'Female', 'Marketing', 11, 76464,
        'Indore', 5, '2021-02-11'],
       [10090, 'Pooja Singh', 45, 'Male', 'Operations', 10, 66160,
        'Bhopal', 2, '2015-08-24'],
       [10091, 'Arjun Singh', 27, 'Female', 'IT', 13, 95472, 'Pune', 1,
        '2016-01-09'],
       [10092, 'Kavya Singh', 32, 'Male', 'HR', 12, 78116, 'Mumbai', 2,
        '2017-12-25'],
       [10093, 'Amit Singh', 44, 'Female', 'Finance', 3, 65163, 'Delhi',
        4, '2012-11-13'],
       [10094, 'Riya Singh', 37, 'Male', 'Sales', 14, 82370, 'Bengaluru',
        2, '2022-04-28'],
       [10095, 'Karan Singh', 31, 'Female', 'Marketing', 6, 63796,
        'Hyderabad', 2, '2012-07-12'],
       [10096, 'Nisha Singh', 28, 'Male', 'Operations', 11, 73476,
        'Jaipur', 3, '2018-04-01'],
       [10097, 'Varun Singh', 24, 'Female', 'IT', 14, 93994, 'Indore', 3,
        '2023-06-05'],
       [10098, 'Simran Singh', 43, 'Male', 'HR', 7, 68186, 'Bhopal', 3,
        '2012-08-14'],
       [10099, 'Deepak Singh', 30, 'Female', 'Finance', 2, 63730, 'Pune',
        5, '2017-12-14'],
       [10100, 'Meena Singh', 25, 'Male', 'Sales', 1, 57721, 'Mumbai', 4,
        '2019-10-02']], dtype=object)

In [ ]:
import numpy as np

v = np.array(csv_1)
v

array([[10001, 'Aarav Sharma', 25, 'Female', 'IT', 11, 82061, 'Indore',
        3, '2017-06-29'],
       [10002, 'Priya Sharma', 26, 'Male', 'HR', 4, 56836, 'Bhopal', 5,
        '2013-12-13'],
       [10003, 'Rahul Sharma', 35, 'Female', 'Finance', 10, 75650,
        'Pune', 1, '2014-02-06'],
       [10004, 'Anjali Sharma', 29, 'Male', 'Sales', 4, 65136, 'Mumbai',
        5, '2012-08-05'],
       [10005, 'Aman Sharma', 28, 'Female', 'Marketing', 9, 78694,
        'Delhi', 5, '2021-05-29'],
       [10006, 'Neha Sharma', 36, 'Male', 'Operations', 4, 58824,
        'Bengaluru', 3, '2012-02-23'],
       [10007, 'Rohit Sharma', 27, 'Female', 'IT', 13, 103077,
        'Hyderabad', 4, '2019-08-19'],
       [10008, 'Sneha Sharma', 26, 'Male', 'HR', 5, 59700, 'Jaipur', 3,
        '2014-04-17'],
       [10009, 'Vikas Sharma', 34, 'Female', 'Finance', 2, 63396,
        'Indore', 3, '2019-09-18'],
       [10010, 'Pooja Sharma', 30, 'Male', 'Sales', 10, 70880, 'Bhopal',
        4, '2024-01-10'],
       [10011, 'Arjun Sharma', 34, 'Female', 'Marketing', 2, 55322,
        'Pune', 5, '2018-07-29'],
       [10012, 'Kavya Sharma', 42, 'Male', 'Operations', 14, 86724,
        'Mumbai', 3, '2024-12-12'],
       [10013, 'Amit Sharma', 44, 'Female', 'IT', 4, 71568, 'Delhi', 1,
        '2017-02-09'],
       [10014, 'Riya Sharma', 31, 'Male', 'HR', 13, 71619, 'Bengaluru',
        2, '2014-04-07'],
       [10015, 'Karan Sharma', 30, 'Female', 'Finance', 7, 76996,
        'Hyderabad', 3, '2015-08-25'],
       [10016, 'Nisha Sharma', 33, 'Male', 'Sales', 6, 66574, 'Jaipur',
        3, '2013-08-07'],
       [10017, 'Varun Sharma', 42, 'Female', 'Marketing', 10, 70500,
        'Indore', 5, '2017-06-28'],
       [10018, 'Simran Sharma', 36, 'Male', 'Operations', 3, 54831,
        'Bhopal', 3, '2024-06-28'],
       [10019, 'Deepak Sharma', 43, 'Female', 'IT', 4, 73656, 'Pune', 1,
        '2017-02-19'],
       [10020, 'Meena Sharma', 23, 'Male', 'HR', 14, 80044, 'Mumbai', 4,
        '2018-01-02'],
       [10021, 'Aarav Patel', 28, 'Female', 'Finance', 2, 65322, 'Delhi',
        3, '2016-10-07'],
       [10022, 'Priya Patel', 37, 'Male', 'Sales', 11, 80410,
        'Bengaluru', 4, '2015-03-16'],
       [10023, 'Rahul Patel', 26, 'Female', 'Marketing', 5, 62025,
        'Hyderabad', 5, '2024-02-02'],
       [10024, 'Anjali Patel', 45, 'Male', 'Operations', 5, 61485,
        'Jaipur', 4, '2025-02-01'],
       [10025, 'Aman Patel', 33, 'Female', 'IT', 7, 78643, 'Indore', 2,
        '2023-06-06'],
       [10026, 'Neha Patel', 24, 'Male', 'HR', 8, 62768, 'Bhopal', 1,
        '2015-06-06'],
       [10027, 'Rohit Patel', 27, 'Female', 'Finance', 11, 91823, 'Pune',
        4, '2025-05-17'],
       [10028, 'Sneha Patel', 34, 'Male', 'Sales', 2, 59562, 'Mumbai', 5,
        '2022-07-01'],
       [10029, 'Vikas Patel', 30, 'Female', 'Marketing', 9, 75697,
        'Delhi', 1, '2014-07-27'],
       [10030, 'Pooja Patel', 39, 'Male', 'Operations', 11, 70506,
        'Bengaluru', 3, '2014-07-02'],
       [10031, 'Arjun Patel', 35, 'Female', 'IT', 5, 74115, 'Hyderabad',
        4, '2012-01-27'],
       [10032, 'Kavya Patel', 45, 'Male', 'HR', 12, 74468, 'Jaipur', 5,
        '2016-01-03'],
       [10033, 'Amit Patel', 25, 'Female', 'Finance', 9, 85020, 'Indore',
        3, '2023-05-21'],
       [10034, 'Riya Patel', 28, 'Male', 'Sales', 10, 73130, 'Bhopal', 3,
        '2015-08-16'],
       [10035, 'Karan Patel', 38, 'Female', 'Marketing', 9, 65509,
        'Pune', 5, '2019-04-09'],
       [10036, 'Nisha Patel', 22, 'Male', 'Operations', 8, 61832,
        'Mumbai', 3, '2018-11-24'],
       [10037, 'Varun Patel', 23, 'Female', 'IT', 4, 72972, 'Delhi', 5,
        '2013-10-07'],
       [10038, 'Simran Patel', 45, 'Male', 'HR', 2, 54990, 'Bengaluru',
        1, '2023-12-12'],
       [10039, 'Deepak Patel', 26, 'Female', 'Finance', 13, 82906,
        'Hyderabad', 4, '2024-04-30'],
       [10040, 'Meena Patel', 30, 'Male', 'Sales', 3, 62740, 'Jaipur', 5,
        '2021-06-28'],
       [10041, 'Aarav Verma', 39, 'Female', 'Marketing', 4, 63976,
        'Indore', 2, '2018-12-28'],
       [10042, 'Priya Verma', 43, 'Male', 'Operations', 7, 67810,
        'Bhopal', 3, '2021-10-28'],
       [10043, 'Rahul Verma', 38, 'Female', 'IT', 15, 101360, 'Pune', 1,
        '2017-07-23'],
       [10044, 'Anjali Verma', 24, 'Male', 'HR', 4, 58768, 'Mumbai', 1,
        '2025-03-12'],
       [10045, 'Aman Verma', 29, 'Female', 'Finance', 9, 84345, 'Delhi',
        2, '2012-02-28'],
       [10046, 'Neha Verma', 44, 'Male', 'Sales', 2, 60584, 'Bengaluru',
        1, '2017-02-18'],
       [10047, 'Rohit Verma', 23, 'Female', 'Marketing', 2, 56352,
        'Hyderabad', 1, '2023-07-13'],
       [10048, 'Sneha Verma', 30, 'Male', 'Operations', 4, 59480,
        'Jaipur', 4, '2016-10-21'],
       [10049, 'Vikas Verma', 26, 'Female', 'IT', 9, 91829, 'Indore', 5,
        '2024-12-03'],
       [10050, 'Pooja Verma', 29, 'Male', 'HR', 8, 69744, 'Bhopal', 4,
        '2016-04-08'],
       [10051, 'Arjun Verma', 25, 'Female', 'Finance', 2, 65698, 'Pune',
        4, '2019-12-12'],
       [10052, 'Kavya Verma', 35, 'Male', 'Sales', 7, 72192, 'Mumbai', 1,
        '2014-03-17'],
       [10053, 'Amit Verma', 34, 'Female', 'Marketing', 1, 54991,
        'Delhi', 3, '2014-06-14'],
       [10054, 'Riya Verma', 28, 'Male', 'Operations', 4, 55556,
        'Bengaluru', 5, '2022-01-23'],
       [10055, 'Karan Verma', 35, 'Female', 'IT', 3, 70625, 'Hyderabad',
        3, '2022-05-17'],
       [10056, 'Nisha Verma', 24, 'Male', 'HR', 4, 59628, 'Jaipur', 5,
        '2014-03-13'],
       [10057, 'Varun Verma', 42, 'Female', 'Finance', 1, 62607,
        'Indore', 1, '2014-02-03'],
       [10058, 'Simran Verma', 29, 'Male', 'Sales', 15, 82600, 'Bhopal',
        4, '2022-11-22'],
       [10059, 'Deepak Verma', 28, 'Female', 'Marketing', 8, 70568,
        'Pune', 1, '2015-09-10'],
       [10060, 'Meena Verma', 22, 'Male', 'Operations', 7, 64093,
        'Mumbai', 3, '2022-03-16'],
       [10061, 'Aarav Gupta', 35, 'Female', 'IT', 5, 79630, 'Delhi', 5,
        '2022-11-30'],
       [10062, 'Priya Gupta', 28, 'Male', 'HR', 3, 56321, 'Bengaluru', 2,
        '2013-04-24'],
       [10063, 'Rahul Gupta', 45, 'Female', 'Finance', 10, 86100,
        'Hyderabad', 1, '2019-01-13'],
       [10064, 'Anjali Gupta', 23, 'Male', 'Sales', 1, 57696, 'Jaipur',
        4, '2023-04-12'],
       [10065, 'Aman Gupta', 38, 'Female', 'Marketing', 15, 79330,
        'Indore', 1, '2023-05-23'],
       [10066, 'Neha Gupta', 27, 'Male', 'Operations', 2, 51280,
        'Bhopal', 5, '2013-07-10'],
       [10067, 'Rohit Gupta', 29, 'Female', 'IT', 11, 90586, 'Pune', 1,
        '2024-10-10'],
       [10068, 'Sneha Gupta', 40, 'Male', 'HR', 4, 60868, 'Mumbai', 1,
        '2013-11-02'],
       [10069, 'Vikas Gupta', 43, 'Female', 'Finance', 7, 78865, 'Delhi',
        5, '2023-09-22'],
       [10070, 'Pooja Gupta', 30, 'Male', 'Sales', 6, 66508, 'Bengaluru',
        3, '2017-05-09'],
       [10071, 'Arjun Gupta', 34, 'Female', 'Marketing', 5, 60840,
        'Hyderabad', 3, '2022-04-03'],
       [10072, 'Kavya Gupta', 24, 'Male', 'Operations', 6, 57114,
        'Jaipur', 4, '2024-08-17'],
       [10073, 'Amit Gupta', 24, 'Female', 'IT', 2, 70202, 'Indore', 2,
        '2023-05-07'],
       [10074, 'Riya Gupta', 26, 'Male', 'HR', 5, 61070, 'Bhopal', 1,
        '2017-06-24'],
       [10075, 'Karan Gupta', 31, 'Female', 'Finance', 6, 70938, 'Pune',
        4, '2024-03-08'],
       [10076, 'Nisha Gupta', 31, 'Male', 'Sales', 12, 88024, 'Mumbai',
        5, '2012-03-05'],
       [10077, 'Varun Gupta', 39, 'Female', 'Marketing', 11, 75243,
        'Delhi', 1, '2015-01-05'],
       [10078, 'Simran Gupta', 25, 'Male', 'Operations', 5, 56595,
        'Bengaluru', 5, '2015-06-27'],
       [10079, 'Deepak Gupta', 31, 'Female', 'IT', 5, 78690, 'Hyderabad',
        2, '2019-09-09'],
       [10080, 'Meena Gupta', 43, 'Male', 'HR', 4, 61192, 'Jaipur', 3,
        '2023-05-03'],
       [10081, 'Aarav Singh', 30, 'Female', 'Finance', 8, 72832,
        'Indore', 1, '2021-07-01'],
       [10082, 'Priya Singh', 30, 'Male', 'Sales', 14, 77260, 'Bhopal',
        1, '2019-06-25'],
       [10083, 'Rahul Singh', 26, 'Female', 'Marketing', 13, 88452,
        'Pune', 3, '2015-08-16'],
       [10084, 'Anjali Singh', 36, 'Male', 'Operations', 12, 79548,
        'Mumbai', 4, '2024-07-30'],
       [10085, 'Aman Singh', 25, 'Female', 'IT', 1, 66654, 'Delhi', 2,
        '2024-03-27'],
       [10086, 'Neha Singh', 33, 'Male', 'HR', 1, 52692, 'Bengaluru', 5,
        '2015-04-28'],
       [10087, 'Rohit Singh', 26, 'Female', 'Finance', 7, 71095,
        'Hyderabad', 3, '2020-03-06'],
       [10088, 'Sneha Singh', 23, 'Male', 'Sales', 15, 88480, 'Jaipur',
        2, '2017-08-06'],
       [10089, 'Vikas Singh', 25, 'Female', 'Marketing', 11, 76464,
        'Indore', 5, '2021-02-11'],
       [10090, 'Pooja Singh', 45, 'Male', 'Operations', 10, 66160,
        'Bhopal', 2, '2015-08-24'],
       [10091, 'Arjun Singh', 27, 'Female', 'IT', 13, 95472, 'Pune', 1,
        '2016-01-09'],
       [10092, 'Kavya Singh', 32, 'Male', 'HR', 12, 78116, 'Mumbai', 2,
        '2017-12-25'],
       [10093, 'Amit Singh', 44, 'Female', 'Finance', 3, 65163, 'Delhi',
        4, '2012-11-13'],
       [10094, 'Riya Singh', 37, 'Male', 'Sales', 14, 82370, 'Bengaluru',
        2, '2022-04-28'],
       [10095, 'Karan Singh', 31, 'Female', 'Marketing', 6, 63796,
        'Hyderabad', 2, '2012-07-12'],
       [10096, 'Nisha Singh', 28, 'Male', 'Operations', 11, 73476,
        'Jaipur', 3, '2018-04-01'],
       [10097, 'Varun Singh', 24, 'Female', 'IT', 14, 93994, 'Indore', 3,
        '2023-06-05'],
       [10098, 'Simran Singh', 43, 'Male', 'HR', 7, 68186, 'Bhopal', 3,
        '2012-08-14'],
       [10099, 'Deepak Singh', 30, 'Female', 'Finance', 2, 63730, 'Pune',
        5, '2017-12-14'],
       [10100, 'Meena Singh', 25, 'Male', 'Sales', 1, 57721, 'Mumbai', 4,
        '2019-10-02']], dtype=object)

In [ ]:
csv_1.sort_index(axis=0, ascending=False)

,Employee_ID,Name,Age,Gender,Department,Experience_Years,Salary,City,Performance_Score,Joining_Date
99,10100,Meena Singh,25,Male,Sales,1,57721,Mumbai,4,2019-10-02
98,10099,Deepak Singh,30,Female,Finance,2,63730,Pune,5,2017-12-14
97,10098,Simran Singh,43,Male,HR,7,68186,Bhopal,3,2012-08-14
96,10097,Varun Singh,24,Female,IT,14,93994,Indore,3,2023-06-05
95,10096,Nisha Singh,28,Male,Operations,11,73476,Jaipur,3,2018-04-01
...,...,...,...,...,...,...,...,...,...,...
4,10005,Aman Sharma,28,Female,Marketing,9,78694,Delhi,5,2021-05-29
3,10004,Anjali Sharma,29,Male,Sales,4,65136,Mumbai,5,2012-08-05
2,10003,Rahul Sharma,35,Female,Finance,10,75650,Pune,1,2014-02-06
1,10002,Priya Sharma,26,Male,HR,4,56836,Bhopal,5,2013-12-13
0,10001,Aarav Sharma,25,Female,IT,11,82061,Indore,3,2017-06-29

In [ ]:
csv_1['Department'][0] = 'python'
csv_1

/tmp/ipykernel_3989/3448181976.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  csv_1['Department'][0] = 'python'
/tmp/ipykernel_3989/3448181976.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  csv_1['Department'][0] = 'python'

,Employee_ID,Name,Age,Gender,Department,Experience_Years,Salary,City,Performance_Score,Joining_Date
0,10001,Aarav Sharma,25,Female,python,11,82061,Indore,3,2017-06-29
1,10002,Priya Sharma,26,Male,HR,4,56836,Bhopal,5,2013-12-13
2,10003,Rahul Sharma,35,Female,Finance,10,75650,Pune,1,2014-02-06
3,10004,Anjali Sharma,29,Male,Sales,4,65136,Mumbai,5,2012-08-05
4,10005,Aman Sharma,28,Female,Marketing,9,78694,Delhi,5,2021-05-29
...,...,...,...,...,...,...,...,...,...,...
95,10096,Nisha Singh,28,Male,Operations,11,73476,Jaipur,3,2018-04-01
96,10097,Varun Singh,24,Female,IT,14,93994,Indore,3,2023-06-05
97,10098,Simran Singh,43,Male,HR,7,68186,Bhopal,3,2012-08-14
98,10099,Deepak Singh,30,Female,Finance,2,63730,Pune,5,2017-12-14
99,10100,Meena Singh,25,Male,Sales,1,57721,Mumbai,4,2019-10-02

In [ ]:
csv_1.loc[0,"Employee_Name"] = "python"
csv_1

,Employee_ID,Name,Age,Gender,Department,Experience_Years,Salary,City,Performance_Score,Joining_Date,Employee_Name
0,10001,Aarav Sharma,25,Female,python,11,82061,Indore,3,2017-06-29,python
1,10002,Priya Sharma,26,Male,HR,4,56836,Bhopal,5,2013-12-13,NaN
2,10003,Rahul Sharma,35,Female,Finance,10,75650,Pune,1,2014-02-06,NaN
3,10004,Anjali Sharma,29,Male,Sales,4,65136,Mumbai,5,2012-08-05,NaN
4,10005,Aman Sharma,28,Female,Marketing,9,78694,Delhi,5,2021-05-29,NaN
...,...,...,...,...,...,...,...,...,...,...,...
95,10096,Nisha Singh,28,Male,Operations,11,73476,Jaipur,3,2018-04-01,NaN
96,10097,Varun Singh,24,Female,IT,14,93994,Indore,3,2023-06-05,NaN
97,10098,Simran Singh,43,Male,HR,7,68186,Bhopal,3,2012-08-14,NaN
98,10099,Deepak Singh,30,Female,Finance,2,63730,Pune,5,2017-12-14,NaN
99,10100,Meena Singh,25,Male,Sales,1,57721,Mumbai,4,2019-10-02,NaN

In [ ]:
csv_1.loc[[2,3],["Name","Gender"]]

            Name  Gender
2   Rahul Sharma  Female
3  Anjali Sharma    Male

In [ ]:
csv_1.loc[:,["Name","Gender"]]

             Name  Gender
0    Aarav Sharma  Female
1    Priya Sharma    Male
2    Rahul Sharma  Female
3   Anjali Sharma    Male
4     Aman Sharma  Female
..            ...     ...
95    Nisha Singh    Male
96    Varun Singh  Female
97   Simran Singh    Male
98   Deepak Singh  Female
99    Meena Singh    Male

[100 rows x 2 columns]

In [ ]:
csv_1.loc[2:3,:]

,Employee_ID,Name,Age,Gender,Department,Experience_Years,Salary,City,Performance_Score,Joining_Date,Employee_Name
2,10003,Rahul Sharma,35,Female,Finance,10,75650,Pune,1,2014-02-06,NaN
3,10004,Anjali Sharma,29,Male,Sales,4,65136,Mumbai,5,2012-08-05,NaN

In [ ]:
csv_1.iloc[0,1]

'Aarav Sharma'

In [ ]:
csv_1.drop('Experience_Years',axis=1)

,Employee_ID,Name,Age,Gender,Department,Salary,City,Performance_Score,Joining_Date,Employee_Name
0,10001,Aarav Sharma,25,Female,python,82061,Indore,3,2017-06-29,python
1,10002,Priya Sharma,26,Male,HR,56836,Bhopal,5,2013-12-13,NaN
2,10003,Rahul Sharma,35,Female,Finance,75650,Pune,1,2014-02-06,NaN
3,10004,Anjali Sharma,29,Male,Sales,65136,Mumbai,5,2012-08-05,NaN
4,10005,Aman Sharma,28,Female,Marketing,78694,Delhi,5,2021-05-29,NaN
...,...,...,...,...,...,...,...,...,...,...
95,10096,Nisha Singh,28,Male,Operations,73476,Jaipur,3,2018-04-01,NaN
96,10097,Varun Singh,24,Female,IT,93994,Indore,3,2023-06-05,NaN
97,10098,Simran Singh,43,Male,HR,68186,Bhopal,3,2012-08-14,NaN
98,10099,Deepak Singh,30,Female,Finance,63730,Pune,5,2017-12-14,NaN
99,10100,Meena Singh,25,Male,Sales,57721,Mumbai,4,2019-10-02,NaN

In [ ]:
csv_1.drop(0,axis=0)

,Employee_ID,Name,Age,Gender,Department,Experience_Years,Salary,City,Performance_Score,Joining_Date,Employee_Name
1,10002,Priya Sharma,26,Male,HR,4,56836,Bhopal,5,2013-12-13,NaN
2,10003,Rahul Sharma,35,Female,Finance,10,75650,Pune,1,2014-02-06,NaN
3,10004,Anjali Sharma,29,Male,Sales,4,65136,Mumbai,5,2012-08-05,NaN
4,10005,Aman Sharma,28,Female,Marketing,9,78694,Delhi,5,2021-05-29,NaN
5,10006,Neha Sharma,36,Male,Operations,4,58824,Bengaluru,3,2012-02-23,NaN
...,...,...,...,...,...,...,...,...,...,...,...
95,10096,Nisha Singh,28,Male,Operations,11,73476,Jaipur,3,2018-04-01,NaN
96,10097,Varun Singh,24,Female,IT,14,93994,Indore,3,2023-06-05,NaN
97,10098,Simran Singh,43,Male,HR,7,68186,Bhopal,3,2012-08-14,NaN
98,10099,Deepak Singh,30,Female,Finance,2,63730,Pune,5,2017-12-14,NaN
99,10100,Meena Singh,25,Male,Sales,1,57721,Mumbai,4,2019-10-02,NaN