<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/Pandas_Dropna_%26_fillna.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Dropna & fillna

Missing Values


| Function    | Definition                  |
| ----------- | --------------------------- |
| `isnull()`  | Missing values check        |
| `isna()`    | Missing values check        |
| `notnull()` | Non-missing values check    |
| `dropna()`  | Missing rows/columns delete |
| `fillna()`  | Missing values fill         |

In [ ]:
import pandas as pd

var = pd.read_csv("/content/missing_data.csv")
var

,Employee_ID,Name,Age,Department,Salary,City,Experience,Performance,Email
0,1001,Priyanka,20.0,IT,50000.0,Indore,1.0,4.0,priyanka@example.com
1,1002,Rahul,NaN,HR,45000.0,NaN,2.0,NaN,rahul@example.com
2,1003,Anjali,21.0,NaN,NaN,Bhopal,NaN,5.0,NaN
3,1004,Aman,23.0,Sales,55000.0,Pune,3.0,3.0,aman@example.com
4,1005,Neha,NaN,IT,62000.0,Mumbai,4.0,NaN,neha@example.com
5,1006,Rohit,25.0,Finance,NaN,NaN,5.0,4.0,NaN
6,1007,Sneha,22.0,NaN,48000.0,Delhi,NaN,2.0,sneha@example.com
7,1008,Vikas,NaN,IT,70000.0,Indore,6.0,NaN,vikas@example.com
8,1009,Pooja,24.0,Marketing,NaN,NaN,2.0,5.0,NaN
9,1010,Arjun,21.0,HR,46000.0,Jaipur,NaN,3.0,arjun@example.com

In [ ]:
var.dropna()

,Employee_ID,Name,Age,Department,Salary,City,Experience,Performance,Email
0,1001,Priyanka,20.0,IT,50000.0,Indore,1.0,4.0,priyanka@example.com
3,1004,Aman,23.0,Sales,55000.0,Pune,3.0,3.0,aman@example.com

In [ ]:
var.dropna(axis=1)

   Employee_ID      Name
0         1001  Priyanka
1         1002     Rahul
2         1003    Anjali
3         1004      Aman
4         1005      Neha
5         1006     Rohit
6         1007     Sneha
7         1008     Vikas
8         1009     Pooja
9         1010     Arjun

In [ ]:
import pandas as pd

var = pd.read_csv("/content/missing_data.csv")
var

,Employee_ID,Name,Age,Department,Salary,City,Experience,Performance,Email
0,1001.0,Priyanka,20.0,IT,50000.0,Indore,1.0,4.0,priyanka@example.com
1,1002.0,Rahul,NaN,HR,45000.0,NaN,2.0,NaN,rahul@example.com
2,1003.0,Anjali,21.0,NaN,NaN,Bhopal,NaN,5.0,NaN
3,1004.0,Aman,23.0,Sales,55000.0,Pune,3.0,3.0,aman@example.com
4,1005.0,Neha,NaN,IT,62000.0,Mumbai,4.0,NaN,neha@example.com
5,1006.0,Rohit,25.0,Finance,NaN,NaN,5.0,4.0,NaN
6,1007.0,Sneha,22.0,NaN,48000.0,Delhi,NaN,2.0,sneha@example.com
7,1008.0,Vikas,NaN,IT,70000.0,Indore,6.0,NaN,vikas@example.com
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1010.0,Arjun,21.0,HR,46000.0,Jaipur,NaN,3.0,arjun@example.com

In [ ]:
var.dropna(how="any")

,Employee_ID,Name,Age,Department,Salary,City,Experience,Performance,Email
0,1001.0,Priyanka,20.0,IT,50000.0,Indore,1.0,4.0,priyanka@example.com
3,1004.0,Aman,23.0,Sales,55000.0,Pune,3.0,3.0,aman@example.com

In [ ]:
var.dropna(how="all")

,Employee_ID,Name,Age,Department,Salary,City,Experience,Performance,Email
0,1001.0,Priyanka,20.0,IT,50000.0,Indore,1.0,4.0,priyanka@example.com
1,1002.0,Rahul,NaN,HR,45000.0,NaN,2.0,NaN,rahul@example.com
2,1003.0,Anjali,21.0,NaN,NaN,Bhopal,NaN,5.0,NaN
3,1004.0,Aman,23.0,Sales,55000.0,Pune,3.0,3.0,aman@example.com
4,1005.0,Neha,NaN,IT,62000.0,Mumbai,4.0,NaN,neha@example.com
5,1006.0,Rohit,25.0,Finance,NaN,NaN,5.0,4.0,NaN
6,1007.0,Sneha,22.0,NaN,48000.0,Delhi,NaN,2.0,sneha@example.com
7,1008.0,Vikas,NaN,IT,70000.0,Indore,6.0,NaN,vikas@example.com
9,1010.0,Arjun,21.0,HR,46000.0,Jaipur,NaN,3.0,arjun@example.com

In [ ]:
var.dropna(subset=["Email"])

,Employee_ID,Name,Age,Department,Salary,City,Experience,Performance,Email
0,1001.0,Priyanka,20.0,IT,50000.0,Indore,1.0,4.0,priyanka@example.com
1,1002.0,Rahul,NaN,HR,45000.0,NaN,2.0,NaN,rahul@example.com
3,1004.0,Aman,23.0,Sales,55000.0,Pune,3.0,3.0,aman@example.com
4,1005.0,Neha,NaN,IT,62000.0,Mumbai,4.0,NaN,neha@example.com
6,1007.0,Sneha,22.0,NaN,48000.0,Delhi,NaN,2.0,sneha@example.com
7,1008.0,Vikas,NaN,IT,70000.0,Indore,6.0,NaN,vikas@example.com
9,1010.0,Arjun,21.0,HR,46000.0,Jaipur,NaN,3.0,arjun@example.com

In [ ]:
var.dropna(inplace=True)
var

,Employee_ID,Name,Age,Department,Salary,City,Experience,Performance,Email
0,1001.0,Priyanka,20.0,IT,50000.0,Indore,1.0,4.0,priyanka@example.com
3,1004.0,Aman,23.0,Sales,55000.0,Pune,3.0,3.0,aman@example.com

In [ ]:
var.dropna(thresh=8)
var

,Employee_ID,Name,Age,Department,Salary,City,Experience,Performance,Email
0,1001.0,Priyanka,20.0,IT,50000.0,Indore,1.0,4.0,priyanka@example.com
3,1004.0,Aman,23.0,Sales,55000.0,Pune,3.0,3.0,aman@example.com

In [ ]:
# fillna

In [ ]:
import pandas as pd

var = pd.read_csv("/content/missing_data.csv")
var

,Employee_ID,Name,Age,Department,Salary,City,Experience,Performance,Email
0,1001.0,Priyanka,20.0,IT,50000.0,Indore,1.0,4.0,priyanka@example.com
1,1002.0,Rahul,NaN,HR,45000.0,NaN,2.0,NaN,rahul@example.com
2,1003.0,Anjali,21.0,NaN,NaN,Bhopal,NaN,5.0,NaN
3,1004.0,Aman,23.0,Sales,55000.0,Pune,3.0,3.0,aman@example.com
4,1005.0,Neha,NaN,IT,62000.0,Mumbai,4.0,NaN,neha@example.com
5,1006.0,Rohit,25.0,Finance,NaN,NaN,5.0,4.0,NaN
6,1007.0,Sneha,22.0,NaN,48000.0,Delhi,NaN,2.0,sneha@example.com
7,1008.0,Vikas,NaN,IT,70000.0,Indore,6.0,NaN,vikas@example.com
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1010.0,Arjun,21.0,HR,46000.0,Jaipur,NaN,3.0,arjun@example.com

In [ ]:
var.fillna("python")

,Employee_ID,Name,Age,Department,Salary,City,Experience,Performance,Email
0,1001.0,Priyanka,20.0,IT,50000.0,Indore,1.0,4.0,priyanka@example.com
1,1002.0,Rahul,python,HR,45000.0,python,2.0,python,rahul@example.com
2,1003.0,Anjali,21.0,python,python,Bhopal,python,5.0,python
3,1004.0,Aman,23.0,Sales,55000.0,Pune,3.0,3.0,aman@example.com
4,1005.0,Neha,python,IT,62000.0,Mumbai,4.0,python,neha@example.com
5,1006.0,Rohit,25.0,Finance,python,python,5.0,4.0,python
6,1007.0,Sneha,22.0,python,48000.0,Delhi,python,2.0,sneha@example.com
7,1008.0,Vikas,python,IT,70000.0,Indore,6.0,python,vikas@example.com
8,python,python,python,python,python,python,python,python,python
9,1010.0,Arjun,21.0,HR,46000.0,Jaipur,python,3.0,arjun@example.com

In [ ]:
import pandas as pd

var = pd.read_csv("/content/missing_data.csv")
var.fillna({"Employee_ID":"Python","Name":"c","Age":"java"})

,Employee_ID,Name,Age,Department,Salary,City,Experience,Performance,Email
0,1001.0,Priyanka,20.0,IT,50000.0,Indore,1.0,4.0,priyanka@example.com
1,1002.0,Rahul,java,HR,45000.0,NaN,2.0,NaN,rahul@example.com
2,1003.0,Anjali,21.0,NaN,NaN,Bhopal,NaN,5.0,NaN
3,1004.0,Aman,23.0,Sales,55000.0,Pune,3.0,3.0,aman@example.com
4,1005.0,Neha,java,IT,62000.0,Mumbai,4.0,NaN,neha@example.com
5,1006.0,Rohit,25.0,Finance,NaN,NaN,5.0,4.0,NaN
6,1007.0,Sneha,22.0,NaN,48000.0,Delhi,NaN,2.0,sneha@example.com
7,1008.0,Vikas,java,IT,70000.0,Indore,6.0,NaN,vikas@example.com
8,Python,c,java,NaN,NaN,NaN,NaN,NaN,NaN
9,1010.0,Arjun,21.0,HR,46000.0,Jaipur,NaN,3.0,arjun@example.com

In [ ]:
var.fillna(method="ffill")      # Previous value

/tmp/ipykernel_2846/3062787689.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  var.fillna(method="ffill")

,Employee_ID,Name,Age,Department,Salary,City,Experience,Performance,Email
0,1001.0,Priyanka,20.0,IT,50000.0,Indore,1.0,4.0,priyanka@example.com
1,1002.0,Rahul,20.0,HR,45000.0,Indore,2.0,4.0,rahul@example.com
2,1003.0,Anjali,21.0,HR,45000.0,Bhopal,2.0,5.0,rahul@example.com
3,1004.0,Aman,23.0,Sales,55000.0,Pune,3.0,3.0,aman@example.com
4,1005.0,Neha,23.0,IT,62000.0,Mumbai,4.0,3.0,neha@example.com
5,1006.0,Rohit,25.0,Finance,62000.0,Mumbai,5.0,4.0,neha@example.com
6,1007.0,Sneha,22.0,Finance,48000.0,Delhi,5.0,2.0,sneha@example.com
7,1008.0,Vikas,22.0,IT,70000.0,Indore,6.0,2.0,vikas@example.com
8,1008.0,Vikas,22.0,IT,70000.0,Indore,6.0,2.0,vikas@example.com
9,1010.0,Arjun,21.0,HR,46000.0,Jaipur,6.0,3.0,arjun@example.com

In [ ]:
var.fillna(method="bfill")         # Next value

/tmp/ipykernel_2846/119153051.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  var.fillna(method="bfill")

,Employee_ID,Name,Age,Department,Salary,City,Experience,Performance,Email
0,1001.0,Priyanka,20.0,IT,50000.0,Indore,1.0,4.0,priyanka@example.com
1,1002.0,Rahul,21.0,HR,45000.0,Bhopal,2.0,5.0,rahul@example.com
2,1003.0,Anjali,21.0,Sales,55000.0,Bhopal,3.0,5.0,aman@example.com
3,1004.0,Aman,23.0,Sales,55000.0,Pune,3.0,3.0,aman@example.com
4,1005.0,Neha,25.0,IT,62000.0,Mumbai,4.0,4.0,neha@example.com
5,1006.0,Rohit,25.0,Finance,48000.0,Delhi,5.0,4.0,sneha@example.com
6,1007.0,Sneha,22.0,IT,48000.0,Delhi,6.0,2.0,sneha@example.com
7,1008.0,Vikas,21.0,IT,70000.0,Indore,6.0,3.0,vikas@example.com
8,1010.0,Arjun,21.0,HR,46000.0,Jaipur,NaN,3.0,arjun@example.com
9,1010.0,Arjun,21.0,HR,46000.0,Jaipur,NaN,3.0,arjun@example.com

In [ ]:
var.fillna(method="bfill",axis=1)

/tmp/ipykernel_2846/249782568.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  var.fillna(method="bfill",axis=1)
/tmp/ipykernel_2846/249782568.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  var.fillna(method="bfill",axis=1)

,Employee_ID,Name,Age,Department,Salary,City,Experience,Performance,Email
0,1001.0,Priyanka,20.0,IT,50000.0,Indore,1.0,4.0,priyanka@example.com
1,1002.0,Rahul,HR,HR,45000.0,2.0,2.0,rahul@example.com,rahul@example.com
2,1003.0,Anjali,21.0,Bhopal,Bhopal,Bhopal,5.0,5.0,NaN
3,1004.0,Aman,23.0,Sales,55000.0,Pune,3.0,3.0,aman@example.com
4,1005.0,Neha,IT,IT,62000.0,Mumbai,4.0,neha@example.com,neha@example.com
5,1006.0,Rohit,25.0,Finance,5.0,5.0,5.0,4.0,NaN
6,1007.0,Sneha,22.0,48000.0,48000.0,Delhi,2.0,2.0,sneha@example.com
7,1008.0,Vikas,IT,IT,70000.0,Indore,6.0,vikas@example.com,vikas@example.com
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1010.0,Arjun,21.0,HR,46000.0,Jaipur,3.0,3.0,arjun@example.com

In [ ]:
var.fillna(5,inplace=True)
var

,Employee_ID,Name,Age,Department,Salary,City,Experience,Performance,Email
0,1001.0,Priyanka,20.0,IT,50000.0,Indore,1.0,4.0,priyanka@example.com
1,1002.0,Rahul,5.0,HR,45000.0,5,2.0,5.0,rahul@example.com
2,1003.0,Anjali,21.0,5,5.0,Bhopal,5.0,5.0,5
3,1004.0,Aman,23.0,Sales,55000.0,Pune,3.0,3.0,aman@example.com
4,1005.0,Neha,5.0,IT,62000.0,Mumbai,4.0,5.0,neha@example.com
5,1006.0,Rohit,25.0,Finance,5.0,5,5.0,4.0,5
6,1007.0,Sneha,22.0,5,48000.0,Delhi,5.0,2.0,sneha@example.com
7,1008.0,Vikas,5.0,IT,70000.0,Indore,6.0,5.0,vikas@example.com
8,5.0,5,5.0,5,5.0,5,5.0,5.0,5
9,1010.0,Arjun,21.0,HR,46000.0,Jaipur,5.0,3.0,arjun@example.com

In [ ]:
var.fillna("python",limit=2)

,Employee_ID,Name,Age,Department,Salary,City,Experience,Performance,Email
0,1001.0,Priyanka,20.0,IT,50000.0,Indore,1.0,4.0,priyanka@example.com
1,1002.0,Rahul,5.0,HR,45000.0,5,2.0,5.0,rahul@example.com
2,1003.0,Anjali,21.0,5,5.0,Bhopal,5.0,5.0,5
3,1004.0,Aman,23.0,Sales,55000.0,Pune,3.0,3.0,aman@example.com
4,1005.0,Neha,5.0,IT,62000.0,Mumbai,4.0,5.0,neha@example.com
5,1006.0,Rohit,25.0,Finance,5.0,5,5.0,4.0,5
6,1007.0,Sneha,22.0,5,48000.0,Delhi,5.0,2.0,sneha@example.com
7,1008.0,Vikas,5.0,IT,70000.0,Indore,6.0,5.0,vikas@example.com
8,5.0,5,5.0,5,5.0,5,5.0,5.0,5
9,1010.0,Arjun,21.0,HR,46000.0,Jaipur,5.0,3.0,arjun@example.com