<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/Pandas_ArithmeticOperation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 # ArithmeticOperation

In [ ]:
import pandas as pd

var = pd.DataFrame({"A":[1,2,3,4,5],"B":[5,6,7,8,9]})

var

   A  B
0  1  5
1  2  6
2  3  7
3  4  8
4  5  9

In [ ]:
var["c"] = var["A"]+var["B"]

var

   A  B   c
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12
4  5  9  14

In [ ]:
var["c"] = var["A"]- var["B"]

var

   A  B  c
0  1  5 -4
1  2  6 -4
2  3  7 -4
3  4  8 -4
4  5  9 -4

In [ ]:
var["c"] = var["A"] * var["B"]

var

   A  B   c
0  1  5   5
1  2  6  12
2  3  7  21
3  4  8  32

In [ ]:
var["c"] = var["A"] / var["B"]

var

   A  B         c
0  1  5  0.200000
1  2  6  0.333333
2  3  7  0.428571
3  4  8  0.500000

In [ ]:
var["c"] = var["A"] % var["B"]

var

   A  B  c
0  1  5  1
1  2  6  2
2  3  7  3
3  4  8  4

In [ ]:
var1 = pd.DataFrame({"A":[10,20,30,40],"B":[15,16,17,18]})

var1

    A   B
0  10  15
1  20  16
2  30  17
3  40  18

In [ ]:
var1["Python"] = var1["A"] <= 20
var1['Python_1'] = var1["B"] >= 16

var1

    A   B  Python  Python_1
0  10  15    True     False
1  20  16    True      True
2  30  17   False      True
3  40  18   False      True

In [ ]:
# Insert pandas

In [ ]:
import pandas as pd                                                         # df.insert(position, "column_name", value)
                                                                               #insert() → DataFrame me kisi particular position par new column add karta hai.

var = pd.DataFrame({"A":[1,2,3,4,5],"B":[5,6,7,8,9],"c":[11,12,13,14,15]})

var

   A  B   c
0  1  5  11
1  2  6  12
2  3  7  13
3  4  8  14
4  5  9  15

In [ ]:
var.insert(1, "python",var["A"])

var

   A  python  B
0  1       1  5
1  2       2  6
2  3       3  7
3  4       4  8
4  5       5  9

In [ ]:
var.insert(1,"python_1",[11,12,13,14,15])

var

   A  python_1  python  B
0  1        11       1  5
1  2        12       2  6
2  3        13       3  7
3  4        14       4  8
4  5        15       5  9

In [ ]:
var["python_12"] = var["A"][:3]

var

   A  python_1  python  B  python_12
0  1        11       1  5        1.0
1  2        12       2  6        2.0
2  3        13       3  7        3.0
3  4        14       4  8        NaN
4  5        15       5  9        NaN

In [ ]:
# Delete

| Function   | Use               |
| ---------- | ----------------- |
| `insert()` | New column add    |
| `drop()`   | Row/column delete |
| `axis=0`   | Row               |
| `axis=1`   | Column            |



INSERT → Add Column

DROP   → Delete Row/Column

In [ ]:
var1 = var.pop("B")              # drop() → DataFrame se row ya column delete karta hai.

var1                             # axis=1 → Column delete

                                 # axis=0 → Row delete

0    5
1    6
2    7
3    8
4    9
Name: B, dtype: int64

In [ ]:
var

   A   c
0  1  11
1  2  12
2  3  13
3  4  14
4  5  15

In [ ]:
del var["A"]

var

    c
0  11
1  12
2  13
3  14
4  15

In [ ]:
# Row Delete

import pandas as pd

data = {
    "Name": ["Priyanka", "Rahul", "Aman"],
    "Age": [20, 21, 22]
}

df = pd.DataFrame(data)
                                    # Index 1 wali row delete:
df = df.drop(1, axis=0)

print(df)

       Name  Age
0  Priyanka   20
2      Aman   22

In [ ]:
# Multiple Columns Delete                           # Ek saath multiple columns delete kar sakte hain.

df = df.drop(["Name", "Age"], axis=1)

In [ ]:
# Multiple Rows Delete                                 # Ek saath multiple rows delete kar sakte hain.

df = df.drop([0, 2], axis=0)

In [ ]:
# CSV file ke saath

#Agar aapke paas data.csv hai:

import pandas as pd

df = pd.read_csv("data.csv")

# Insert
df.insert(1, "Country", "India")

# Delete column
df = df.drop("Country", axis=1)

# Save
df.to_csv("new_data.csv", index=False)