<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/Pandas_Groupby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Groupby

In [ ]:
import pandas as pd

var = pd.DataFrame({"name":["a","b","c","d","a","b","a","b","a","c","c","c"],
                    "S_1":[12,13,14,12,13,15,43,25,16,23,44,65],
                    "S_2":[12,13,14,12,13,15,43,25,16,23,43,55]})

var

   name  S_1  S_2
0     a   12   12
1     b   13   13
2     c   14   14
3     d   12   12
4     a   13   13
5     b   15   15
6     a   43   43
7     b   25   25
8     a   16   16
9     c   23   23
10    c   44   43
11    c   65   55

In [ ]:
var_new = var.groupby("name")

var_new

In [ ]:
for x,y in var_new:
  print(x)
  print(y)
  print()

a
  name  S_1  S_2
0    a   12   12
4    a   13   13
6    a   43   43
8    a   16   16

b
  name  S_1  S_2
1    b   13   13
5    b   15   15
7    b   25   25

c
   name  S_1  S_2
2     c   14   14
9     c   23   23
10    c   44   43
11    c   65   55

d
  name  S_1  S_2
3    d   12   12

In [ ]:
var_new.get_group("a")

  name  S_1  S_2
0    a   12   12
4    a   13   13
6    a   43   43
8    a   16   16

In [ ]:
var_new.get_group("d")

  name  S_1  S_2
3    d   12   12

In [ ]:
var_new.min()

      S_1  S_2
name
a      12   12
b      13   13
c      14   14
d      12   12

In [ ]:
var_new.max()

      S_1  S_2
name
a      43   43
b      25   25
c      65   55
d      12   12

In [ ]:
var_new.mean()

            S_1        S_2
name
a     21.000000  21.000000
b     17.666667  17.666667
c     36.500000  33.750000
d     12.000000  12.000000

In [ ]:
li = list(var_new)
li

[('a',
    name  S_1  S_2
  0    a   12   12
  4    a   13   13
  6    a   43   43
  8    a   16   16),
 ('b',
    name  S_1  S_2
  1    b   13   13
  5    b   15   15
  7    b   25   25),
 ('c',
     name  S_1  S_2
  2     c   14   14
  9     c   23   23
  10    c   44   43
  11    c   65   55),
 ('d',
    name  S_1  S_2
  3    d   12   12)]