<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/Pandas_join_%26_Append.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Join

In [ ]:
import pandas as pd

var1 = pd.DataFrame({'A':[1,2,3,4],'B':[10,20,30,40]})
var2 = pd.DataFrame({'C':[10,20,30,40],'D':[100,200,300,400]})

var1.join(var2)

   A   B   C    D
0  1  10  10  100
1  2  20  20  200
2  3  30  30  300
3  4  40  40  400

In [ ]:
import pandas as pd

var1 = pd.DataFrame({'A':[1,2,3,4],'B':[10,20,30,40]})
var2 = pd.DataFrame({'C':[10,20],'D':[100,200]})

var1.join(var2)

   A   B     C      D
0  1  10  10.0  100.0
1  2  20  20.0  200.0
2  3  30   NaN    NaN
3  4  40   NaN    NaN

In [ ]:
import pandas as pd

var1 = pd.DataFrame({'A':[1,2,3,4],'B':[10,20,30,40]},index=["a","b","c","d"])
var2 = pd.DataFrame({'C':[10,20],'D':[100,200]},index=["a","b"])

var2.join(var1)

    C    D  A   B
a  10  100  1  10
b  20  200  2  20

In [ ]:
import pandas as pd

var1 = pd.DataFrame({'A':[1,2,3,4],'B':[10,20,30,40]},index=["a","b","c","d"])
var2 = pd.DataFrame({'C':[10,20],'D':[100,200]},index=["a","b"])

# var2.join(var1,how="left")
# var2.join(var1,how="right")
# var2.join(var1,how="outer")
var2.join(var1,how="inner")

    C    D  A   B
a  10  100  1  10
b  20  200  2  20

In [ ]:
var1 = pd.DataFrame({'A':[1,2,3,4],'B':[10,20,30,40]},index=["a","b","c","d"])
var2 = pd.DataFrame({'C':[10,20],'B':[100,200]},index=["a","b"])

var2.join(var1,how="outer",lsuffix="_12")

      C   B_12  A   B
a  10.0  100.0  1  10
b  20.0  200.0  2  20
c   NaN    NaN  3  30
d   NaN    NaN  4  40

In [ ]:
var1 = pd.DataFrame({'A':[1,2,3,4],'B':[10,20,30,40]},index=["a","b","c","d"])
var2 = pd.DataFrame({'C':[10,20],'B':[100,200]},index=["a","b"])

var2.join(var1,how="outer",lsuffix="_12",rsuffix="_123")

      C   B_12  A  B_123
a  10.0  100.0  1     10
b  20.0  200.0  2     20
c   NaN    NaN  3     30
d   NaN    NaN  4     40

In [ ]:
# Append

In [ ]:
import pandas as pd

var1 = pd.DataFrame({'A':[1,2,3,4],'B':[10,20,30,40]},index=["a","b","c","d"])
var2 = pd.DataFrame({'C':[10,20],'B':[100,200]},index=["a","b"])

# var1.append(var2) # The .append() method is deprecated and removed
pd.concat([var1, var2]) # Use pd.concat() instead

     A    B     C
a  1.0   10   NaN
b  2.0   20   NaN
c  3.0   30   NaN
d  4.0   40   NaN
a  NaN  100  10.0
b  NaN  200  20.0

In [ ]:
var1 = pd.DataFrame({'A':[1,2,3,4],'B':[10,20,30,40]})
var2 = pd.DataFrame({'C':[10,20],'B':[100,200]})

# var1.append(var2) # The .append() method is deprecated and removed
pd.concat([var1, var2]) # Use pd.concat() instead

     A    B     C
0  1.0   10   NaN
1  2.0   20   NaN
2  3.0   30   NaN
3  4.0   40   NaN
0  NaN  100  10.0
1  NaN  200  20.0

In [ ]:
import pandas as pd

var1 = pd.DataFrame({'A':[1,2,3,4],'B':[10,20,30,40]})
var2 = pd.DataFrame({'C':[10,20],'B':[100,200]})

# var1.append(var2,ignore_index=True) # The .append() method is deprecated and removed
pd.concat([var1, var2], ignore_index=True) # Use pd.concat() instead with ignore_index

     A    B     C
0  1.0   10   NaN
1  2.0   20   NaN
2  3.0   30   NaN
3  4.0   40   NaN
4  NaN  100  10.0
5  NaN  200  20.0

In [ ]:
import pandas as pd

var1 = pd.DataFrame({'A':[1,2,3,4],'B':[10,20,30,40]})
var2 = pd.DataFrame({'C':[10,20],'D':[100,200]})

# var1.append(var2,ignore_index=True) # The .append() method is deprecated and removed
pd.concat([var1, var2], ignore_index=True) # Use pd.concat() instead with ignore_index

     A     B     C      D
0  1.0  10.0   NaN    NaN
1  2.0  20.0   NaN    NaN
2  3.0  30.0   NaN    NaN
3  4.0  40.0   NaN    NaN
4  NaN   NaN  10.0  100.0
5  NaN   NaN  20.0  200.0