<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/Pandas_CSV_File.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Write CSV

Important CSV + Pandas Functions Cheat Sheet



| Function               | Easy Definition         |
| ---------------------- | ----------------------- |
| `pd.read_csv()`        | CSV read karna          |
| `df.to_csv()`          | CSV save karna          |
| `df.head()`            | Starting rows           |
| `df.tail()`            | Last rows               |
| `df.info()`            | Data information        |
| `df.describe()`        | Statistics              |
| `df.shape`             | Rows + columns          |
| `df.columns`           | Column names            |
| `df.dtypes`            | Data types              |
| `df.loc[]`             | Label se data select    |
| `df.iloc[]`            | Position se data select |
| `df.isnull()`          | Missing values check    |
| `df.dropna()`          | Missing rows delete     |
| `df.fillna()`          | Missing values fill     |
| `df.duplicated()`      | Duplicate check         |
| `df.drop_duplicates()` | Duplicate delete        |
| `df.rename()`          | Name change             |
| `df.drop()`            | Row/column delete       |
| `df.insert()`          | Column insert           |
| `df.sort_values()`     | Data sorting            |
| `df.unique()`          | Unique values           |
| `df.nunique()`         | Unique count            |
| `df.value_counts()`    | Values ki frequency     |
| `df.replace()`         | Value replace           |
| `df.astype()`          | Data type change        |
| `df.groupby()`         | Data grouping           |
| `df.mean()`            | Average                 |
| `df.sum()`             | Total                   |
| `df.max()`             | Maximum                 |
| `df.min()`             | Minimum                 |
| `df.count()`           | Count                   |
| `df.query()`           | Condition filtering     |

In [ ]:
import pandas as pd                                                    #CSV file ko Pandas me open/read karne ke liye use hota hai.

dis = {"a":[1,2,3,4,5,6],"s":[1,2,3,4,5,6],"d":[1,2,3,4,5,6]}

d = pd.DataFrame(dis)

print(d)
d.to_csv("Test_new.csv")

   a  s  d
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5
5  6  6  6

In [ ]:
import pandas as pd                                                   #df.to_csv--> #DataFrame ko CSV file me save karta hai.
                                                                       #index=False → extra index column save nahi karega.
dis = {"a":[1,2,3,4,5,6],"s":[1,2,3,4,5,9],"d":[1,2,3,4,5,6]}

d = pd.DataFrame(dis)

print(d)
d.to_csv("Test_new1.csv",index=False,header=[1,2,3])

   a  s  d
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5
5  6  9  6

In [ ]:
# Read CSV

In [ ]:
import pandas as pd
df = pd.read_csv("/content/pandas_sales_50_rows.csv")
df

,Order_ID,Date,Product,Category,Region,Quantity,Unit_Price,Discount_%,Total_Sales,Profit
0,1001,01-01-2026,Laptop,Electronics,North,5,55000,5,275000,39187.50
1,1002,04-01-2026,Mobile,Electronics,South,12,25000,10,300000,40500.00
2,1003,07-01-2026,Headphones,Accessories,East,25,2000,8,50000,6900.00
3,1004,10-01-2026,Keyboard,Accessories,West,18,1500,5,27000,3847.50
4,1005,13-01-2026,Mouse,Accessories,North,30,800,12,24000,3168.00
5,1006,16-01-2026,Monitor,Electronics,South,8,18000,7,144000,20088.00
6,1007,19-01-2026,Tablet,Electronics,East,10,30000,6,300000,42300.00
7,1008,22-01-2026,Printer,Office,West,6,12000,5,72000,10260.00
8,1009,25-01-2026,Laptop,Electronics,North,7,55000,10,385000,51975.00
9,1010,28-01-2026,Mobile,Electronics,South,15,25000,8,375000,51750.00
10,1011,31-01-2026,Laptop,Electronics,North,20,55000,5,1100000,156750.00
11,1012,03-02-2026,Mobile,Electronics,South,9,25000,10,225000,30375.00
12,1013,06-02-2026,Headphones,Accessories,East,11,2000,8,22000,3036.00
13,1014,09-02-2026,Keyboard,Accessories,West,14,1500,5,21000,2992.50
14,1015,12-02-2026,Mouse,Accessories,North,22,800,12,17600,2323.20
15,1016,15-02-2026,Monitor,Electronics,South,40,18000,7,720000,100440.00
16,1017,18-02-2026,Tablet,Electronics,East,18,30000,6,540000,76140.00
17,1018,21-02-2026,Printer,Office,West,5,12000,5,60000,8550.00
18,1019,24-02-2026,Laptop,Electronics,North,6,55000,10,330000,44550.00
19,1020,27-02-2026,Mobile,Electronics,South,13,25000,8,325000,44850.00
20,1021,02-03-2026,Laptop,Electronics,North,16,55000,5,880000,125400.00
21,1022,05-03-2026,Mobile,Electronics,South,21,25000,10,525000,70875.00
22,1023,08-03-2026,Headphones,Accessories,East,8,2000,8,16000,2208.00
23,1024,11-03-2026,Keyboard,Accessories,West,28,1500,5,42000,5985.00
24,1025,14-03-2026,Mouse,Accessories,North,24,800,12,19200,2534.40
25,1026,17-03-2026,Monitor,Electronics,South,7,18000,7,126000,17577.00
26,1027,20-03-2026,Tablet,Electronics,East,12,30000,6,360000,50760.00
27,1028,23-03-2026,Printer,Office,West,19,12000,5,228000,32490.00
28,1029,26-03-2026,Laptop,Electronics,North,17,55000,10,935000,126225.00
29,1030,29-03-2026,Mobile,Electronics,South,6,25000,8,150000,20700.00
30,1031,01-04-2026,Laptop,Electronics,North,15,55000,5,825000,117562.50
31,1032,04-04-2026,Mobile,Electronics,South,23,25000,10,575000,77625.00
32,1033,07-04-2026,Headphones,Accessories,East,31,2000,8,62000,8556.00
33,1034,10-04-2026,Keyboard,Accessories,West,8,1500,5,12000,1710.00
34,1035,13-04-2026,Mouse,Accessories,North,10,800,12,8000,1056.00
35,1036,16-04-2026,Monitor,Electronics,South,18,18000,7,324000,45198.00
36,1037,19-04-2026,Tablet,Electronics,East,9,30000,6,270000,38070.00
37,1038,22-04-2026,Printer,Office,West,14,12000,5,168000,23940.00
38,1039,25-04-2026,Laptop,Electronics,North,25,55000,10,1375000,185625.00
39,1040,28-04-2026,Mobile,Electronics,South,7,25000,8,175000,24150.00
40,1041,01-05-2026,Laptop,Electronics,North,12,55000,5,660000,94050.00
41,1042,04-05-2026,Mobile,Electronics,South,20,25000,10,500000,67500.00
42,1043,07-05-2026,Headphones,Accessories,East,11,2000,8,22000,3036.00
43,1044,10-05-2026,Keyboard,Accessories,West,35,1500,5,52500,7481.25
44,1045,13-05-2026,Mouse,Accessories,North,13,800,12,10400,1372.80
45,1046,16-05-2026,Monitor,Electronics,South,6,18000,7,108000,15066.00
46,1047,19-05-2026,Tablet,Electronics,East,8,30000,6,240000,33840.00
47,1048,22-05-2026,Printer,Office,West,16,12000,5,192000,27360.00
48,1049,25-05-2026,Laptop,Electronics,North,27,55000,10,1485000,200475.00
49,1050,28-05-2026,Mobile,Electronics,South,10,25000,8,250000,34500.00

In [ ]:
import pandas as pd

csv_1 = pd.read_csv("/content/pandas_sales_50_rows.csv")
csv_1

,Order_ID,Date,Product,Category,Region,Quantity,Unit_Price,Discount_%,Total_Sales,Profit
0,1001,01-01-2026,Laptop,Electronics,North,5,55000,5,275000,39187.50
1,1002,04-01-2026,Mobile,Electronics,South,12,25000,10,300000,40500.00
2,1003,07-01-2026,Headphones,Accessories,East,25,2000,8,50000,6900.00
3,1004,10-01-2026,Keyboard,Accessories,West,18,1500,5,27000,3847.50
4,1005,13-01-2026,Mouse,Accessories,North,30,800,12,24000,3168.00
5,1006,16-01-2026,Monitor,Electronics,South,8,18000,7,144000,20088.00
6,1007,19-01-2026,Tablet,Electronics,East,10,30000,6,300000,42300.00
7,1008,22-01-2026,Printer,Office,West,6,12000,5,72000,10260.00
8,1009,25-01-2026,Laptop,Electronics,North,7,55000,10,385000,51975.00
9,1010,28-01-2026,Mobile,Electronics,South,15,25000,8,375000,51750.00
10,1011,31-01-2026,Laptop,Electronics,North,20,55000,5,1100000,156750.00
11,1012,03-02-2026,Mobile,Electronics,South,9,25000,10,225000,30375.00
12,1013,06-02-2026,Headphones,Accessories,East,11,2000,8,22000,3036.00
13,1014,09-02-2026,Keyboard,Accessories,West,14,1500,5,21000,2992.50
14,1015,12-02-2026,Mouse,Accessories,North,22,800,12,17600,2323.20
15,1016,15-02-2026,Monitor,Electronics,South,40,18000,7,720000,100440.00
16,1017,18-02-2026,Tablet,Electronics,East,18,30000,6,540000,76140.00
17,1018,21-02-2026,Printer,Office,West,5,12000,5,60000,8550.00
18,1019,24-02-2026,Laptop,Electronics,North,6,55000,10,330000,44550.00
19,1020,27-02-2026,Mobile,Electronics,South,13,25000,8,325000,44850.00
20,1021,02-03-2026,Laptop,Electronics,North,16,55000,5,880000,125400.00
21,1022,05-03-2026,Mobile,Electronics,South,21,25000,10,525000,70875.00
22,1023,08-03-2026,Headphones,Accessories,East,8,2000,8,16000,2208.00
23,1024,11-03-2026,Keyboard,Accessories,West,28,1500,5,42000,5985.00
24,1025,14-03-2026,Mouse,Accessories,North,24,800,12,19200,2534.40
25,1026,17-03-2026,Monitor,Electronics,South,7,18000,7,126000,17577.00
26,1027,20-03-2026,Tablet,Electronics,East,12,30000,6,360000,50760.00
27,1028,23-03-2026,Printer,Office,West,19,12000,5,228000,32490.00
28,1029,26-03-2026,Laptop,Electronics,North,17,55000,10,935000,126225.00
29,1030,29-03-2026,Mobile,Electronics,South,6,25000,8,150000,20700.00
30,1031,01-04-2026,Laptop,Electronics,North,15,55000,5,825000,117562.50
31,1032,04-04-2026,Mobile,Electronics,South,23,25000,10,575000,77625.00
32,1033,07-04-2026,Headphones,Accessories,East,31,2000,8,62000,8556.00
33,1034,10-04-2026,Keyboard,Accessories,West,8,1500,5,12000,1710.00
34,1035,13-04-2026,Mouse,Accessories,North,10,800,12,8000,1056.00
35,1036,16-04-2026,Monitor,Electronics,South,18,18000,7,324000,45198.00
36,1037,19-04-2026,Tablet,Electronics,East,9,30000,6,270000,38070.00
37,1038,22-04-2026,Printer,Office,West,14,12000,5,168000,23940.00
38,1039,25-04-2026,Laptop,Electronics,North,25,55000,10,1375000,185625.00
39,1040,28-04-2026,Mobile,Electronics,South,7,25000,8,175000,24150.00
40,1041,01-05-2026,Laptop,Electronics,North,12,55000,5,660000,94050.00
41,1042,04-05-2026,Mobile,Electronics,South,20,25000,10,500000,67500.00
42,1043,07-05-2026,Headphones,Accessories,East,11,2000,8,22000,3036.00
43,1044,10-05-2026,Keyboard,Accessories,West,35,1500,5,52500,7481.25
44,1045,13-05-2026,Mouse,Accessories,North,13,800,12,10400,1372.80
45,1046,16-05-2026,Monitor,Electronics,South,6,18000,7,108000,15066.00
46,1047,19-05-2026,Tablet,Electronics,East,8,30000,6,240000,33840.00
47,1048,22-05-2026,Printer,Office,West,16,12000,5,192000,27360.00
48,1049,25-05-2026,Laptop,Electronics,North,27,55000,10,1485000,200475.00
49,1050,28-05-2026,Mobile,Electronics,South,10,25000,8,250000,34500.00

In [ ]:
csv_2 = pd.read_csv("/content/pandas_sales_50_rows.csv",nrows=2)
csv_2

,Order_ID,Date,Product,Category,Region,Quantity,Unit_Price,Discount_%,Total_Sales,Profit
0,1001,01-01-2026,Laptop,Electronics,North,5,55000,5,275000,39187.5
1,1002,04-01-2026,Mobile,Electronics,South,12,25000,10,300000,40500.0

In [ ]:
csv_2 = pd.read_csv("/content/pandas_sales_50_rows.csv",nrows=2)
print(type(csv_2))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
csv_2 = pd.read_csv("/content/pandas_sales_50_rows.csv",nrows=8)
csv_2

,Order_ID,Date,Product,Category,Region,Quantity,Unit_Price,Discount_%,Total_Sales,Profit
0,1001,01-01-2026,Laptop,Electronics,North,5,55000,5,275000,39187.5
1,1002,04-01-2026,Mobile,Electronics,South,12,25000,10,300000,40500.0
2,1003,07-01-2026,Headphones,Accessories,East,25,2000,8,50000,6900.0
3,1004,10-01-2026,Keyboard,Accessories,West,18,1500,5,27000,3847.5
4,1005,13-01-2026,Mouse,Accessories,North,30,800,12,24000,3168.0
5,1006,16-01-2026,Monitor,Electronics,South,8,18000,7,144000,20088.0
6,1007,19-01-2026,Tablet,Electronics,East,10,30000,6,300000,42300.0
7,1008,22-01-2026,Printer,Office,West,6,12000,5,72000,10260.0

In [ ]:
csv_2 = pd.read_csv("/content/pandas_sales_50_rows.csv",usecols=["Profit"])
csv_2

       Profit
0    39187.50
1    40500.00
2     6900.00
3     3847.50
4     3168.00
5    20088.00
6    42300.00
7    10260.00
8    51975.00
9    51750.00
10  156750.00
11   30375.00
12    3036.00
13    2992.50
14    2323.20
15  100440.00
16   76140.00
17    8550.00
18   44550.00
19   44850.00
20  125400.00
21   70875.00
22    2208.00
23    5985.00
24    2534.40
25   17577.00
26   50760.00
27   32490.00
28  126225.00
29   20700.00
30  117562.50
31   77625.00
32    8556.00
33    1710.00
34    1056.00
35   45198.00
36   38070.00
37   23940.00
38  185625.00
39   24150.00
40   94050.00
41   67500.00
42    3036.00
43    7481.25
44    1372.80
45   15066.00
46   33840.00
47   27360.00
48  200475.00
49   34500.00

In [ ]:
csv_2 = pd.read_csv("/content/pandas_sales_50_rows.csv",usecols=["Profit","Discount_%" ])
csv_2

    Discount_%     Profit
0            5   39187.50
1           10   40500.00
2            8    6900.00
3            5    3847.50
4           12    3168.00
5            7   20088.00
6            6   42300.00
7            5   10260.00
8           10   51975.00
9            8   51750.00
10           5  156750.00
11          10   30375.00
12           8    3036.00
13           5    2992.50
14          12    2323.20
15           7  100440.00
16           6   76140.00
17           5    8550.00
18          10   44550.00
19           8   44850.00
20           5  125400.00
21          10   70875.00
22           8    2208.00
23           5    5985.00
24          12    2534.40
25           7   17577.00
26           6   50760.00
27           5   32490.00
28          10  126225.00
29           8   20700.00
30           5  117562.50
31          10   77625.00
32           8    8556.00
33           5    1710.00
34          12    1056.00
35           7   45198.00
36           6   38070.00
37           5   23940.00
38          10  185625.00
39           8   24150.00
40           5   94050.00
41          10   67500.00
42           8    3036.00
43           5    7481.25
44          12    1372.80
45           7   15066.00
46           6   33840.00
47           5   27360.00
48          10  200475.00
49           8   34500.00

In [ ]:
csv_2 = pd.read_csv("/content/pandas_sales_50_rows.csv",usecols=[0,3])
csv_2

    Order_ID     Category
0       1001  Electronics
1       1002  Electronics
2       1003  Accessories
3       1004  Accessories
4       1005  Accessories
5       1006  Electronics
6       1007  Electronics
7       1008       Office
8       1009  Electronics
9       1010  Electronics
10      1011  Electronics
11      1012  Electronics
12      1013  Accessories
13      1014  Accessories
14      1015  Accessories
15      1016  Electronics
16      1017  Electronics
17      1018       Office
18      1019  Electronics
19      1020  Electronics
20      1021  Electronics
21      1022  Electronics
22      1023  Accessories
23      1024  Accessories
24      1025  Accessories
25      1026  Electronics
26      1027  Electronics
27      1028       Office
28      1029  Electronics
29      1030  Electronics
30      1031  Electronics
31      1032  Electronics
32      1033  Accessories
33      1034  Accessories
34      1035  Accessories
35      1036  Electronics
36      1037  Electronics
37      1038       Office
38      1039  Electronics
39      1040  Electronics
40      1041  Electronics
41      1042  Electronics
42      1043  Accessories
43      1044  Accessories
44      1045  Accessories
45      1046  Electronics
46      1047  Electronics
47      1048       Office
48      1049  Electronics
49      1050  Electronics

In [ ]:
csv_1.head()                             # Starting ki 5 rows dikhata hai.

,Order_ID,Date,Product,Category,Region,Quantity,Unit_Price,Discount_%,Total_Sales,Profit
0,1001,01-01-2026,Laptop,Electronics,North,5,55000,5,275000,39187.5
1,1002,04-01-2026,Mobile,Electronics,South,12,25000,10,300000,40500.0
2,1003,07-01-2026,Headphones,Accessories,East,25,2000,8,50000,6900.0
3,1004,10-01-2026,Keyboard,Accessories,West,18,1500,5,27000,3847.5
4,1005,13-01-2026,Mouse,Accessories,North,30,800,12,24000,3168.0

In [ ]:
csv_1.tail()                        # Last ki 5 rows dikhata hai.

,Order_ID,Date,Product,Category,Region,Quantity,Unit_Price,Discount_%,Total_Sales,Profit
45,1046,16-05-2026,Monitor,Electronics,South,6,18000,7,108000,15066.0
46,1047,19-05-2026,Tablet,Electronics,East,8,30000,6,240000,33840.0
47,1048,22-05-2026,Printer,Office,West,16,12000,5,192000,27360.0
48,1049,25-05-2026,Laptop,Electronics,North,27,55000,10,1485000,200475.0
49,1050,28-05-2026,Mobile,Electronics,South,10,25000,8,250000,34500.0

In [ ]:
csv_1.dtypes           # Har column ka data type batata hai.

Order_ID         int64
Date            object
Product         object
Category        object
Region          object
Quantity         int64
Unit_Price       int64
Discount_%       int64
Total_Sales      int64
Profit         float64
dtype: object

In [ ]:
csv_1.info()              # Columns, data types aur non-null values ki information deta hai.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     50 non-null     int64
 1   Date         50 non-null     object
 2   Product      50 non-null     object
 3   Category     50 non-null     object
 4   Region       50 non-null     object
 5   Quantity     50 non-null     int64
 6   Unit_Price   50 non-null     int64
 7   Discount_%   50 non-null     int64
 8   Total_Sales  50 non-null     int64
 9   Profit       50 non-null     float64
dtypes: float64(1), int64(5), object(4)
memory usage: 4.0+ KB

In [ ]:
csv_3 = pd.read_csv("/content/pandas_sales_50_rows.csv",skiprows=3)             #skiprows()
                                                                                # df = pd.read_csv("data.csv", skiprows=2)

                                                                                #Definition: Starting ki specified rows ko skip karta hai.
csv_3

,1003,07-01-2026,Headphones,Accessories,East,25,2000,8,50000,6900
0,1004,10-01-2026,Keyboard,Accessories,West,18,1500,5,27000,3847.50
1,1005,13-01-2026,Mouse,Accessories,North,30,800,12,24000,3168.00
2,1006,16-01-2026,Monitor,Electronics,South,8,18000,7,144000,20088.00
3,1007,19-01-2026,Tablet,Electronics,East,10,30000,6,300000,42300.00
4,1008,22-01-2026,Printer,Office,West,6,12000,5,72000,10260.00
5,1009,25-01-2026,Laptop,Electronics,North,7,55000,10,385000,51975.00
6,1010,28-01-2026,Mobile,Electronics,South,15,25000,8,375000,51750.00
7,1011,31-01-2026,Laptop,Electronics,North,20,55000,5,1100000,156750.00
8,1012,03-02-2026,Mobile,Electronics,South,9,25000,10,225000,30375.00
9,1013,06-02-2026,Headphones,Accessories,East,11,2000,8,22000,3036.00
10,1014,09-02-2026,Keyboard,Accessories,West,14,1500,5,21000,2992.50
11,1015,12-02-2026,Mouse,Accessories,North,22,800,12,17600,2323.20
12,1016,15-02-2026,Monitor,Electronics,South,40,18000,7,720000,100440.00
13,1017,18-02-2026,Tablet,Electronics,East,18,30000,6,540000,76140.00
14,1018,21-02-2026,Printer,Office,West,5,12000,5,60000,8550.00
15,1019,24-02-2026,Laptop,Electronics,North,6,55000,10,330000,44550.00
16,1020,27-02-2026,Mobile,Electronics,South,13,25000,8,325000,44850.00
17,1021,02-03-2026,Laptop,Electronics,North,16,55000,5,880000,125400.00
18,1022,05-03-2026,Mobile,Electronics,South,21,25000,10,525000,70875.00
19,1023,08-03-2026,Headphones,Accessories,East,8,2000,8,16000,2208.00
20,1024,11-03-2026,Keyboard,Accessories,West,28,1500,5,42000,5985.00
21,1025,14-03-2026,Mouse,Accessories,North,24,800,12,19200,2534.40
22,1026,17-03-2026,Monitor,Electronics,South,7,18000,7,126000,17577.00
23,1027,20-03-2026,Tablet,Electronics,East,12,30000,6,360000,50760.00
24,1028,23-03-2026,Printer,Office,West,19,12000,5,228000,32490.00
25,1029,26-03-2026,Laptop,Electronics,North,17,55000,10,935000,126225.00
26,1030,29-03-2026,Mobile,Electronics,South,6,25000,8,150000,20700.00
27,1031,01-04-2026,Laptop,Electronics,North,15,55000,5,825000,117562.50
28,1032,04-04-2026,Mobile,Electronics,South,23,25000,10,575000,77625.00
29,1033,07-04-2026,Headphones,Accessories,East,31,2000,8,62000,8556.00
30,1034,10-04-2026,Keyboard,Accessories,West,8,1500,5,12000,1710.00
31,1035,13-04-2026,Mouse,Accessories,North,10,800,12,8000,1056.00
32,1036,16-04-2026,Monitor,Electronics,South,18,18000,7,324000,45198.00
33,1037,19-04-2026,Tablet,Electronics,East,9,30000,6,270000,38070.00
34,1038,22-04-2026,Printer,Office,West,14,12000,5,168000,23940.00
35,1039,25-04-2026,Laptop,Electronics,North,25,55000,10,1375000,185625.00
36,1040,28-04-2026,Mobile,Electronics,South,7,25000,8,175000,24150.00
37,1041,01-05-2026,Laptop,Electronics,North,12,55000,5,660000,94050.00
38,1042,04-05-2026,Mobile,Electronics,South,20,25000,10,500000,67500.00
39,1043,07-05-2026,Headphones,Accessories,East,11,2000,8,22000,3036.00
40,1044,10-05-2026,Keyboard,Accessories,West,35,1500,5,52500,7481.25
41,1045,13-05-2026,Mouse,Accessories,North,13,800,12,10400,1372.80
42,1046,16-05-2026,Monitor,Electronics,South,6,18000,7,108000,15066.00
43,1047,19-05-2026,Tablet,Electronics,East,8,30000,6,240000,33840.00
44,1048,22-05-2026,Printer,Office,West,16,12000,5,192000,27360.00
45,1049,25-05-2026,Laptop,Electronics,North,27,55000,10,1485000,200475.00
46,1050,28-05-2026,Mobile,Electronics,South,10,25000,8,250000,34500.00

In [ ]:
csv_2 = pd.read_csv("/content/pandas_sales_50_rows.csv",index_col="Order_ID")         #index_col
                                                                                      #df = pd.read_csv("data.csv", index_col=0)
                                                                                      #First column ko index bana deta hai.
csv_2

,Date,Product,Category,Region,Quantity,Unit_Price,Discount_%,Total_Sales,Profit
Order_ID,,,,,,,,,
1001,01-01-2026,Laptop,Electronics,North,5,55000,5,275000,39187.50
1002,04-01-2026,Mobile,Electronics,South,12,25000,10,300000,40500.00
1003,07-01-2026,Headphones,Accessories,East,25,2000,8,50000,6900.00
1004,10-01-2026,Keyboard,Accessories,West,18,1500,5,27000,3847.50
1005,13-01-2026,Mouse,Accessories,North,30,800,12,24000,3168.00
1006,16-01-2026,Monitor,Electronics,South,8,18000,7,144000,20088.00
1007,19-01-2026,Tablet,Electronics,East,10,30000,6,300000,42300.00
1008,22-01-2026,Printer,Office,West,6,12000,5,72000,10260.00
1009,25-01-2026,Laptop,Electronics,North,7,55000,10,385000,51975.00
1010,28-01-2026,Mobile,Electronics,South,15,25000,8,375000,51750.00
1011,31-01-2026,Laptop,Electronics,North,20,55000,5,1100000,156750.00
1012,03-02-2026,Mobile,Electronics,South,9,25000,10,225000,30375.00
1013,06-02-2026,Headphones,Accessories,East,11,2000,8,22000,3036.00
1014,09-02-2026,Keyboard,Accessories,West,14,1500,5,21000,2992.50
1015,12-02-2026,Mouse,Accessories,North,22,800,12,17600,2323.20
1016,15-02-2026,Monitor,Electronics,South,40,18000,7,720000,100440.00
1017,18-02-2026,Tablet,Electronics,East,18,30000,6,540000,76140.00
1018,21-02-2026,Printer,Office,West,5,12000,5,60000,8550.00
1019,24-02-2026,Laptop,Electronics,North,6,55000,10,330000,44550.00
1020,27-02-2026,Mobile,Electronics,South,13,25000,8,325000,44850.00
1021,02-03-2026,Laptop,Electronics,North,16,55000,5,880000,125400.00
1022,05-03-2026,Mobile,Electronics,South,21,25000,10,525000,70875.00
1023,08-03-2026,Headphones,Accessories,East,8,2000,8,16000,2208.00
1024,11-03-2026,Keyboard,Accessories,West,28,1500,5,42000,5985.00
1025,14-03-2026,Mouse,Accessories,North,24,800,12,19200,2534.40
1026,17-03-2026,Monitor,Electronics,South,7,18000,7,126000,17577.00
1027,20-03-2026,Tablet,Electronics,East,12,30000,6,360000,50760.00
1028,23-03-2026,Printer,Office,West,19,12000,5,228000,32490.00
1029,26-03-2026,Laptop,Electronics,North,17,55000,10,935000,126225.00
1030,29-03-2026,Mobile,Electronics,South,6,25000,8,150000,20700.00
1031,01-04-2026,Laptop,Electronics,North,15,55000,5,825000,117562.50
1032,04-04-2026,Mobile,Electronics,South,23,25000,10,575000,77625.00
1033,07-04-2026,Headphones,Accessories,East,31,2000,8,62000,8556.00
1034,10-04-2026,Keyboard,Accessories,West,8,1500,5,12000,1710.00
1035,13-04-2026,Mouse,Accessories,North,10,800,12,8000,1056.00
1036,16-04-2026,Monitor,Electronics,South,18,18000,7,324000,45198.00
1037,19-04-2026,Tablet,Electronics,East,9,30000,6,270000,38070.00
1038,22-04-2026,Printer,Office,West,14,12000,5,168000,23940.00
1039,25-04-2026,Laptop,Electronics,North,25,55000,10,1375000,185625.00
1040,28-04-2026,Mobile,Electronics,South,7,25000,8,175000,24150.00
1041,01-05-2026,Laptop,Electronics,North,12,55000,5,660000,94050.00
1042,04-05-2026,Mobile,Electronics,South,20,25000,10,500000,67500.00
1043,07-05-2026,Headphones,Accessories,East,11,2000,8,22000,3036.00
1044,10-05-2026,Keyboard,Accessories,West,35,1500,5,52500,7481.25
1045,13-05-2026,Mouse,Accessories,North,13,800,12,10400,1372.80
1046,16-05-2026,Monitor,Electronics,South,6,18000,7,108000,15066.00
1047,19-05-2026,Tablet,Electronics,East,8,30000,6,240000,33840.00
1048,22-05-2026,Printer,Office,West,16,12000,5,192000,27360.00
1049,25-05-2026,Laptop,Electronics,North,27,55000,10,1485000,200475.00
1050,28-05-2026,Mobile,Electronics,South,10,25000,8,250000,34500.00

In [ ]:
csv_2 = pd.read_csv("/content/pandas_sales_50_rows.csv",header=2)

csv_2

,1002,04-01-2026,Mobile,Electronics,South,12,25000,10,300000,40500
0,1003,07-01-2026,Headphones,Accessories,East,25,2000,8,50000,6900.00
1,1004,10-01-2026,Keyboard,Accessories,West,18,1500,5,27000,3847.50
2,1005,13-01-2026,Mouse,Accessories,North,30,800,12,24000,3168.00
3,1006,16-01-2026,Monitor,Electronics,South,8,18000,7,144000,20088.00
4,1007,19-01-2026,Tablet,Electronics,East,10,30000,6,300000,42300.00
5,1008,22-01-2026,Printer,Office,West,6,12000,5,72000,10260.00
6,1009,25-01-2026,Laptop,Electronics,North,7,55000,10,385000,51975.00
7,1010,28-01-2026,Mobile,Electronics,South,15,25000,8,375000,51750.00
8,1011,31-01-2026,Laptop,Electronics,North,20,55000,5,1100000,156750.00
9,1012,03-02-2026,Mobile,Electronics,South,9,25000,10,225000,30375.00
10,1013,06-02-2026,Headphones,Accessories,East,11,2000,8,22000,3036.00
11,1014,09-02-2026,Keyboard,Accessories,West,14,1500,5,21000,2992.50
12,1015,12-02-2026,Mouse,Accessories,North,22,800,12,17600,2323.20
13,1016,15-02-2026,Monitor,Electronics,South,40,18000,7,720000,100440.00
14,1017,18-02-2026,Tablet,Electronics,East,18,30000,6,540000,76140.00
15,1018,21-02-2026,Printer,Office,West,5,12000,5,60000,8550.00
16,1019,24-02-2026,Laptop,Electronics,North,6,55000,10,330000,44550.00
17,1020,27-02-2026,Mobile,Electronics,South,13,25000,8,325000,44850.00
18,1021,02-03-2026,Laptop,Electronics,North,16,55000,5,880000,125400.00
19,1022,05-03-2026,Mobile,Electronics,South,21,25000,10,525000,70875.00
20,1023,08-03-2026,Headphones,Accessories,East,8,2000,8,16000,2208.00
21,1024,11-03-2026,Keyboard,Accessories,West,28,1500,5,42000,5985.00
22,1025,14-03-2026,Mouse,Accessories,North,24,800,12,19200,2534.40
23,1026,17-03-2026,Monitor,Electronics,South,7,18000,7,126000,17577.00
24,1027,20-03-2026,Tablet,Electronics,East,12,30000,6,360000,50760.00
25,1028,23-03-2026,Printer,Office,West,19,12000,5,228000,32490.00
26,1029,26-03-2026,Laptop,Electronics,North,17,55000,10,935000,126225.00
27,1030,29-03-2026,Mobile,Electronics,South,6,25000,8,150000,20700.00
28,1031,01-04-2026,Laptop,Electronics,North,15,55000,5,825000,117562.50
29,1032,04-04-2026,Mobile,Electronics,South,23,25000,10,575000,77625.00
30,1033,07-04-2026,Headphones,Accessories,East,31,2000,8,62000,8556.00
31,1034,10-04-2026,Keyboard,Accessories,West,8,1500,5,12000,1710.00
32,1035,13-04-2026,Mouse,Accessories,North,10,800,12,8000,1056.00
33,1036,16-04-2026,Monitor,Electronics,South,18,18000,7,324000,45198.00
34,1037,19-04-2026,Tablet,Electronics,East,9,30000,6,270000,38070.00
35,1038,22-04-2026,Printer,Office,West,14,12000,5,168000,23940.00
36,1039,25-04-2026,Laptop,Electronics,North,25,55000,10,1375000,185625.00
37,1040,28-04-2026,Mobile,Electronics,South,7,25000,8,175000,24150.00
38,1041,01-05-2026,Laptop,Electronics,North,12,55000,5,660000,94050.00
39,1042,04-05-2026,Mobile,Electronics,South,20,25000,10,500000,67500.00
40,1043,07-05-2026,Headphones,Accessories,East,11,2000,8,22000,3036.00
41,1044,10-05-2026,Keyboard,Accessories,West,35,1500,5,52500,7481.25
42,1045,13-05-2026,Mouse,Accessories,North,13,800,12,10400,1372.80
43,1046,16-05-2026,Monitor,Electronics,South,6,18000,7,108000,15066.00
44,1047,19-05-2026,Tablet,Electronics,East,8,30000,6,240000,33840.00
45,1048,22-05-2026,Printer,Office,West,16,12000,5,192000,27360.00
46,1049,25-05-2026,Laptop,Electronics,North,27,55000,10,1485000,200475.00
47,1050,28-05-2026,Mobile,Electronics,South,10,25000,8,250000,34500.00

In [ ]:
csv_2 = pd.read_csv("/content/pandas_sales_50_rows.csv",names=["col"])
csv_2

                                                                                                   col
Order_ID Date       Product    Category    Region Quantity Unit_Price Discount_% Total_Sales    Profit
1001     01-01-2026 Laptop     Electronics North  5        55000      5          275000        39187.5
1002     04-01-2026 Mobile     Electronics South  12       25000      10         300000          40500
1003     07-01-2026 Headphones Accessories East   25       2000       8          50000            6900
1004     10-01-2026 Keyboard   Accessories West   18       1500       5          27000          3847.5
1005     13-01-2026 Mouse      Accessories North  30       800        12         24000            3168
1006     16-01-2026 Monitor    Electronics South  8        18000      7          144000          20088
1007     19-01-2026 Tablet     Electronics East   10       30000      6          300000          42300
1008     22-01-2026 Printer    Office      West   6        12000      5          72000           10260
1009     25-01-2026 Laptop     Electronics North  7        55000      10         385000          51975
1010     28-01-2026 Mobile     Electronics South  15       25000      8          375000          51750
1011     31-01-2026 Laptop     Electronics North  20       55000      5          1100000        156750
1012     03-02-2026 Mobile     Electronics South  9        25000      10         225000          30375
1013     06-02-2026 Headphones Accessories East   11       2000       8          22000            3036
1014     09-02-2026 Keyboard   Accessories West   14       1500       5          21000          2992.5
1015     12-02-2026 Mouse      Accessories North  22       800        12         17600          2323.2
1016     15-02-2026 Monitor    Electronics South  40       18000      7          720000         100440
1017     18-02-2026 Tablet     Electronics East   18       30000      6          540000          76140
1018     21-02-2026 Printer    Office      West   5        12000      5          60000            8550
1019     24-02-2026 Laptop     Electronics North  6        55000      10         330000          44550
1020     27-02-2026 Mobile     Electronics South  13       25000      8          325000          44850
1021     02-03-2026 Laptop     Electronics North  16       55000      5          880000         125400
1022     05-03-2026 Mobile     Electronics South  21       25000      10         525000          70875
1023     08-03-2026 Headphones Accessories East   8        2000       8          16000            2208
1024     11-03-2026 Keyboard   Accessories West   28       1500       5          42000            5985
1025     14-03-2026 Mouse      Accessories North  24       800        12         19200          2534.4
1026     17-03-2026 Monitor    Electronics South  7        18000      7          126000          17577
1027     20-03-2026 Tablet     Electronics East   12       30000      6          360000          50760
1028     23-03-2026 Printer    Office      West   19       12000      5          228000          32490
1029     26-03-2026 Laptop     Electronics North  17       55000      10         935000         126225
1030     29-03-2026 Mobile     Electronics South  6        25000      8          150000          20700
1031     01-04-2026 Laptop     Electronics North  15       55000      5          825000       117562.5
1032     04-04-2026 Mobile     Electronics South  23       25000      10         575000          77625
1033     07-04-2026 Headphones Accessories East   31       2000       8          62000            8556
1034     10-04-2026 Keyboard   Accessories West   8        1500       5          12000            1710
1035     13-04-2026 Mouse      Accessories North  10       800        12         8000             1056
1036     16-04-2026 Monitor    Electronics South  18       18000      7          324000          45198
1037     19-04-2026 Tablet     Electronics East   9        30000      6          270000          38070
1038     22-04-2026 Printer    Office      West   14       12000      5          168000          23940
1039     25-04-2026 Laptop     Electronics North  25       55000      10         1375000        185625
1040     28-04-2026 Mobile     Electronics South  7        25000      8          175000          24150
1041     01-05-2026 Laptop     Electronics North  12       55000      5          660000          94050
1042     04-05-2026 Mobile     Electronics South  20       25000      10         500000          67500
1043     07-05-2026 Headphones Accessories East   11       2000       8          22000            3036
1044     10-05-2026 Keyboard   Accessories West   35       1500       5          52500         7481.25
1045     13-05-2026 Mouse      Accessories North  13       800        12         10400          1372.8
1046     16-05-2026 Monitor    Electronics South  6        18000      7          108000          15066
1047     19-05-2026 Tablet     Electronics East   8        30000      6          240000          33840
1048     22-05-2026 Printer    Office      West   16       12000      5          192000          27360
1049     25-05-2026 Laptop     Electronics North  27       55000      10         1485000        200475
1050     28-05-2026 Mobile     Electronics South  10       25000      8          250000          34500

In [ ]:
csv_2 = pd.read_csv("/content/pandas_sales_50_rows.csv",names=["col1","col2","col3","col4","col5","col6","col7","col8","col9","col10"])
csv_2

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10
0,Order_ID,Date,Product,Category,Region,Quantity,Unit_Price,Discount_%,Total_Sales,Profit
1,1001,01-01-2026,Laptop,Electronics,North,5,55000,5,275000,39187.5
2,1002,04-01-2026,Mobile,Electronics,South,12,25000,10,300000,40500
3,1003,07-01-2026,Headphones,Accessories,East,25,2000,8,50000,6900
4,1004,10-01-2026,Keyboard,Accessories,West,18,1500,5,27000,3847.5
5,1005,13-01-2026,Mouse,Accessories,North,30,800,12,24000,3168
6,1006,16-01-2026,Monitor,Electronics,South,8,18000,7,144000,20088
7,1007,19-01-2026,Tablet,Electronics,East,10,30000,6,300000,42300
8,1008,22-01-2026,Printer,Office,West,6,12000,5,72000,10260
9,1009,25-01-2026,Laptop,Electronics,North,7,55000,10,385000,51975
10,1010,28-01-2026,Mobile,Electronics,South,15,25000,8,375000,51750
11,1011,31-01-2026,Laptop,Electronics,North,20,55000,5,1100000,156750
12,1012,03-02-2026,Mobile,Electronics,South,9,25000,10,225000,30375
13,1013,06-02-2026,Headphones,Accessories,East,11,2000,8,22000,3036
14,1014,09-02-2026,Keyboard,Accessories,West,14,1500,5,21000,2992.5
15,1015,12-02-2026,Mouse,Accessories,North,22,800,12,17600,2323.2
16,1016,15-02-2026,Monitor,Electronics,South,40,18000,7,720000,100440
17,1017,18-02-2026,Tablet,Electronics,East,18,30000,6,540000,76140
18,1018,21-02-2026,Printer,Office,West,5,12000,5,60000,8550
19,1019,24-02-2026,Laptop,Electronics,North,6,55000,10,330000,44550
20,1020,27-02-2026,Mobile,Electronics,South,13,25000,8,325000,44850
21,1021,02-03-2026,Laptop,Electronics,North,16,55000,5,880000,125400
22,1022,05-03-2026,Mobile,Electronics,South,21,25000,10,525000,70875
23,1023,08-03-2026,Headphones,Accessories,East,8,2000,8,16000,2208
24,1024,11-03-2026,Keyboard,Accessories,West,28,1500,5,42000,5985
25,1025,14-03-2026,Mouse,Accessories,North,24,800,12,19200,2534.4
26,1026,17-03-2026,Monitor,Electronics,South,7,18000,7,126000,17577
27,1027,20-03-2026,Tablet,Electronics,East,12,30000,6,360000,50760
28,1028,23-03-2026,Printer,Office,West,19,12000,5,228000,32490
29,1029,26-03-2026,Laptop,Electronics,North,17,55000,10,935000,126225
30,1030,29-03-2026,Mobile,Electronics,South,6,25000,8,150000,20700
31,1031,01-04-2026,Laptop,Electronics,North,15,55000,5,825000,117562.5
32,1032,04-04-2026,Mobile,Electronics,South,23,25000,10,575000,77625
33,1033,07-04-2026,Headphones,Accessories,East,31,2000,8,62000,8556
34,1034,10-04-2026,Keyboard,Accessories,West,8,1500,5,12000,1710
35,1035,13-04-2026,Mouse,Accessories,North,10,800,12,8000,1056
36,1036,16-04-2026,Monitor,Electronics,South,18,18000,7,324000,45198
37,1037,19-04-2026,Tablet,Electronics,East,9,30000,6,270000,38070
38,1038,22-04-2026,Printer,Office,West,14,12000,5,168000,23940
39,1039,25-04-2026,Laptop,Electronics,North,25,55000,10,1375000,185625
40,1040,28-04-2026,Mobile,Electronics,South,7,25000,8,175000,24150
41,1041,01-05-2026,Laptop,Electronics,North,12,55000,5,660000,94050
42,1042,04-05-2026,Mobile,Electronics,South,20,25000,10,500000,67500
43,1043,07-05-2026,Headphones,Accessories,East,11,2000,8,22000,3036
44,1044,10-05-2026,Keyboard,Accessories,West,35,1500,5,52500,7481.25
45,1045,13-05-2026,Mouse,Accessories,North,13,800,12,10400,1372.8
46,1046,16-05-2026,Monitor,Electronics,South,6,18000,7,108000,15066
47,1047,19-05-2026,Tablet,Electronics,East,8,30000,6,240000,33840
48,1048,22-05-2026,Printer,Office,West,16,12000,5,192000,27360
49,1049,25-05-2026,Laptop,Electronics,North,27,55000,10,1485000,200475
50,1050,28-05-2026,Mobile,Electronics,South,10,25000,8,250000,34500