<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/Pandas_Pivot_Table_and_melt_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Melt()

data ko reshape karne ke liye use karte hai melt() and pivot function

In [ ]:
import pandas as pd

var = pd.DataFrame({"days":[1,2,3,4,5,6],"eng":[10,12,14,15,16,12],"math":[17,18,19,13,14,16]})

var

   days  eng  math
0     1   10    17
1     2   12    18
2     3   14    19
3     4   15    13
4     5   16    14
5     6   12    16

In [ ]:
pd.melt(var)

   variable  value
0      days      1
1      days      2
2      days      3
3      days      4
4      days      5
5      days      6
6       eng     10
7       eng     12
8       eng     14
9       eng     15
10      eng     16
11      eng     12
12     math     17
13     math     18
14     math     19
15     math     13
16     math     14
17     math     16

In [ ]:
pd.melt(var,id_vars=["days"])

    days variable  value
0      1      eng     10
1      2      eng     12
2      3      eng     14
3      4      eng     15
4      5      eng     16
5      6      eng     12
6      1     math     17
7      2     math     18
8      3     math     19
9      4     math     13
10     5     math     14
11     6     math     16

In [ ]:
pd.melt(var,id_vars=["days"],var_name="python")

    days python  value
0      1    eng     10
1      2    eng     12
2      3    eng     14
3      4    eng     15
4      5    eng     16
5      6    eng     12
6      1   math     17
7      2   math     18
8      3   math     19
9      4   math     13
10     5   math     14
11     6   math     16

In [ ]:
pd.melt(var,id_vars=["days"],var_name="python",value_name="wsjob")

    days python  wsjob
0      1    eng     10
1      2    eng     12
2      3    eng     14
3      4    eng     15
4      5    eng     16
5      6    eng     12
6      1   math     17
7      2   math     18
8      3   math     19
9      4   math     13
10     5   math     14
11     6   math     16

In [ ]:
# Pivot Function #Pivot()

In [ ]:
import pandas as pd

var = pd.DataFrame({"days":[1,2,3,4,5,6],
                    "st_name":["a","b","c","a","b","c"],
                    "eng":[10,12,14,15,16,12],"math":[17,18,19,13,14,16]})

var

   days st_name  eng  math
0     1       a   10    17
1     2       b   12    18
2     3       c   14    19
3     4       a   15    13
4     5       b   16    14
5     6       c   12    16

In [ ]:
var.pivot(index="days",columns="st_name")

          eng              math
st_name     a     b     c     a     b     c
days
1        10.0   NaN   NaN  17.0   NaN   NaN
2         NaN  12.0   NaN   NaN  18.0   NaN
3         NaN   NaN  14.0   NaN   NaN  19.0
4        15.0   NaN   NaN  13.0   NaN   NaN
5         NaN  16.0   NaN   NaN  14.0   NaN
6         NaN   NaN  12.0   NaN   NaN  16.0

In [ ]:
import pandas as pd

var = pd.DataFrame({"days":[1,2,3,4,5,6],
                    "st_name":["a","b","b","a","b","b"],
                    "eng":[10,12,14,15,16,12],"math":[17,18,19,13,14,16]})

var

   days st_name  eng  math
0     1       a   10    17
1     2       b   12    18
2     3       b   14    19
3     4       a   15    13
4     5       b   16    14
5     6       b   12    16

In [ ]:
var.pivot(index="days",columns="st_name")

          eng        math
st_name     a     b     a     b
days
1        10.0   NaN  17.0   NaN
2         NaN  12.0   NaN  18.0
3         NaN  14.0   NaN  19.0
4        15.0   NaN  13.0   NaN
5         NaN  16.0   NaN  14.0
6         NaN  12.0   NaN  16.0

In [ ]:
var.pivot(index="days",columns="st_name",values="eng")

st_name     a     b
days
1        10.0   NaN
2         NaN  12.0
3         NaN  14.0
4        15.0   NaN
5         NaN  16.0
6         NaN  12.0

In [ ]:
import pandas as pd

var = pd.DataFrame({"days":[1,1,1,1,2,2],
                    "st_name":["a","b","b","a","b","b"],
                    "eng":[10,12,14,15,16,12],"math":[17,18,19,13,14,16]})

var

   days st_name  eng  math
0     1       a   10    17
1     1       b   12    18
2     1       b   14    19
3     1       a   15    13
4     2       b   16    14
5     2       b   12    16

In [ ]:
var.pivot_table(index="days",columns="st_name",aggfunc="sum")

          eng        math
st_name     a     b     a     b
days
1        25.0  26.0  30.0  37.0
2         NaN  28.0   NaN  30.0

In [ ]:
var.pivot_table(index="days",columns="st_name",aggfunc="mean")

          eng        math
st_name     a     b     a     b
days
1        12.5  13.0  15.0  18.5
2         NaN  14.0   NaN  15.0

In [ ]:
var.pivot_table(index="days",columns="st_name",aggfunc="sum",margins=True)

          eng            math
st_name     a     b All     a     b All
days
1        25.0  26.0  51  30.0  37.0  67
2         NaN  28.0  28   NaN  30.0  30
All      25.0  54.0  79  30.0  67.0  97