<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/Pandas_Merging_%26_Concat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Merge

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"A":[1,2,3,4],
                    "B":[5,6,7,8]})
var2 = pd.DataFrame({"A":[1,2,3,5],
                    "C":[8,6,3,9]})
pd.merge(var1,var2,on="A")

   A  B  C
0  1  5  8
1  2  6  6
2  3  7  3

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"A":[1,2,3,4],
                    "B":[5,6,7,8]})
var2 = pd.DataFrame({"A":[1,2,3,5],
                    "C":[8,6,3,9]})
pd.merge(var1,var2,how = "left")

   A  B    C
0  1  5  8.0
1  2  6  6.0
2  3  7  3.0
3  4  8  NaN

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"A":[1,2,3,4],
                    "B":[5,6,7,8]})
var2 = pd.DataFrame({"A":[1,2,3,5],
                    "C":[8,6,3,9]})
pd.merge(var1,var2,how = "right")

   A    B  C
0  1  5.0  8
1  2  6.0  6
2  3  7.0  3
3  5  NaN  9

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"A":[1,2,3,4],
                    "B":[5,6,7,8]})
var2 = pd.DataFrame({"A":[1,2,3,5],
                    "C":[8,6,3,9]})
pd.merge(var1,var2,how = "outer")

   A    B    C
0  1  5.0  8.0
1  2  6.0  6.0
2  3  7.0  3.0
3  4  8.0  NaN
4  5  NaN  9.0

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"A":[1,2,3,4],
                    "B":[5,6,7,8]})
var2 = pd.DataFrame({"A":[1,2,3,5],
                    "C":[8,6,3,9]})
pd.merge(var1,var2,how = "outer",indicator=True)

   A    B    C      _merge
0  1  5.0  8.0        both
1  2  6.0  6.0        both
2  3  7.0  3.0        both
3  4  8.0  NaN   left_only
4  5  NaN  9.0  right_only

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"A":[1,2,3,4],
                    "B":[5,6,7,8]})
var2 = pd.DataFrame({"A":[1,2,3,5],
                    "B":[8,6,3,9]})
pd.merge(var1,var2,left_index=True,right_index=True)

   A_x  B_x  A_y  B_y
0    1    5    1    8
1    2    6    2    6
2    3    7    3    3
3    4    8    5    9

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"A":[1,2,3,4],
                    "B":[5,6,7,8]})
var2 = pd.DataFrame({"A":[1,2,3,5],
                    "B":[8,6,3,9]})
pd.merge(var1,var2,left_index=True,right_index=True,suffixes=("name","python"))

   Aname  Bname  Apython  Bpython
0      1      5        1        8
1      2      6        2        6
2      3      7        3        3
3      4      8        5        9

In [ ]:
# Concat

In [ ]:
sr1 = pd.Series([1,2,3,4])
sr2 = pd.Series([11,12,31,41])
pd.concat([sr1,sr2])

0     1
1     2
2     3
3     4
0    11
1    12
2    31
3    41
dtype: int64

In [ ]:
sr1 = pd.Series([1,2,3,4])
sr2 = pd.Series([11,12,31,41])

pd.concat([sr1,sr2])

0     1
1     2
2     3
3     4
0    11
1    12
2    31
3    41
dtype: int64

In [ ]:
d1 = pd.DataFrame({"A":[1,2,3,4],
                    "B":[5,6,7,8]})
d2 = pd.DataFrame({"A":[1,2,3,5],
                    "B":[8,6,3,9]})

pd.concat([d1,d2])

   A  B
0  1  5
1  2  6
2  3  7
3  4  8
0  1  8
1  2  6
2  3  3
3  5  9

In [ ]:
d1 = pd.DataFrame({"A":[1,2,3,4],
                    "B":[5,6,7,8]})
d2 = pd.DataFrame({"A":[1,2,3,5],
                    "C":[8,6,3,9]})
pd.concat([d1,d2],axis=1)

   A  B  A  C
0  1  5  1  8
1  2  6  2  6
2  3  7  3  3
3  4  8  5  9

In [ ]:
d1 = pd.DataFrame({"A":[1,2,3,4],
                    "B":[5,6,7,8]})
d2 = pd.DataFrame({"A":[1,2,],
                    "C":[8,6]})
pd.concat([d1,d2],axis=1,join="inner")

   A  B  A  C
0  1  5  1  8
1  2  6  2  6

In [ ]:
d1 = pd.DataFrame({"A":[1,2,3,4],
                    "B":[5,6,7,8]})
d2 = pd.DataFrame({"A":[1,2,3,4],
                    "C":[21,32,31,11]})
pd.concat([d1,d2],axis=0,join="outer",keys=["first","second"])

          A    B     C
first  0  1  5.0   NaN
       1  2  6.0   NaN
       2  3  7.0   NaN
       3  4  8.0   NaN
second 0  1  NaN  21.0
       1  2  NaN  32.0
       2  3  NaN  31.0
       3  4  NaN  11.0

In [ ]:
d1 = pd.DataFrame({"A":[1,2,3,4],
                    "B":[5,6,7,8]})
d2 = pd.DataFrame({"A":[1,2,3,4],
                    "C":[21,32,31,11]})
pd.concat([d1,d2],axis=1,keys=["d1","d2"])

  d1    d2
   A  B  A   C
0  1  5  1  21
1  2  6  2  32
2  3  7  3  31
3  4  8  4  11

In [ ]:
d1 = pd.DataFrame({"D":[1,2,3,4]})
d2 = pd.DataFrame({"A":[1,2,3,4],"C":[21,32,31,11]})

pd.concat([d1,d2])

     D    A     C
0  1.0  NaN   NaN
1  2.0  NaN   NaN
2  3.0  NaN   NaN
3  4.0  NaN   NaN
0  NaN  1.0  21.0
1  NaN  2.0  32.0
2  NaN  3.0  31.0
3  NaN  4.0  11.0