<a href="https://colab.research.google.com/github/priyanka-chaurasiya/Python/blob/main/Pandas_Replace_%26_Interpolate_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Replace

In [ ]:
import pandas as pd

var = pd.read_csv("/content/stock_volume_14.csv")
var

   Symbol                     Security  Today-Volume  Average-Volume  Change
0    AAPL                   Apple Inc.      58200000        61500000    1.82
1    MSFT              Microsoft Corp.      32100000        29800000   -0.74
2   GOOGL                Alphabet Inc.      24700000        26500000    2.15
3    AMZN              Amazon.com Inc.      41300000        45200000    0.63
4    TSLA                   Tesla Inc.             1        78200000   -1.47
5    NVDA                 NVIDIA Corp.             1       158000000    3.28
6    META          Meta Platforms Inc.             1        21400000    1.12
7    NFLX                 Netflix Inc.             1        10100000   -0.56
8    ORCL                 Oracle Corp.             1        16200000    0.91
9     IBM                    IBM Corp.             1         7200000   -0.32
10   INTC                  Intel Corp.             1        48700000    1.45
11    AMD  Advanced Micro Devices Inc.             1        42100000    2.07
12   CSCO           Cisco Systems Inc.      22100000        23900000   -0.68
13   ADBE                   Adobe Inc.       7300000         8100000    1.36

In [ ]:
var.replace(to_replace=1,value=22)

   Symbol                     Security  Today-Volume  Average-Volume  Change
0    AAPL                   Apple Inc.      58200000        61500000    1.82
1    MSFT              Microsoft Corp.      32100000        29800000   -0.74
2   GOOGL                Alphabet Inc.      24700000        26500000    2.15
3    AMZN              Amazon.com Inc.      41300000        45200000    0.63
4    TSLA                   Tesla Inc.            22        78200000   -1.47
5    NVDA                 NVIDIA Corp.            22       158000000    3.28
6    META          Meta Platforms Inc.            22        21400000    1.12
7    NFLX                 Netflix Inc.            22        10100000   -0.56
8    ORCL                 Oracle Corp.            22        16200000    0.91
9     IBM                    IBM Corp.            22         7200000   -0.32
10   INTC                  Intel Corp.            22        48700000    1.45
11    AMD  Advanced Micro Devices Inc.            22        42100000    2.07
12   CSCO           Cisco Systems Inc.      22100000        23900000   -0.68
13   ADBE                   Adobe Inc.       7300000         8100000    1.36

In [ ]:
var.replace(to_replace="AAPL",value="python")

    Symbol                     Security  Today-Volume  Average-Volume  Change
0   python                   Apple Inc.      58200000        61500000    1.82
1     MSFT              Microsoft Corp.      32100000        29800000   -0.74
2    GOOGL                Alphabet Inc.      24700000        26500000    2.15
3     AMZN              Amazon.com Inc.      41300000        45200000    0.63
4     TSLA                   Tesla Inc.             1        78200000   -1.47
5     NVDA                 NVIDIA Corp.             1       158000000    3.28
6     META          Meta Platforms Inc.             1        21400000    1.12
7     NFLX                 Netflix Inc.             1        10100000   -0.56
8     ORCL                 Oracle Corp.             1        16200000    0.91
9      IBM                    IBM Corp.             1         7200000   -0.32
10    INTC                  Intel Corp.             1        48700000    1.45
11     AMD  Advanced Micro Devices Inc.             1        42100000    2.07
12    CSCO           Cisco Systems Inc.      22100000        23900000   -0.68
13    ADBE                   Adobe Inc.       7300000         8100000    1.36

In [ ]:
var.replace([1,2,3,4,5,6,7,8,9,10,11,12,13],22)

   Symbol                     Security  Today-Volume  Average-Volume  Change
0    AAPL                   Apple Inc.      58200000        61500000    1.82
1    MSFT              Microsoft Corp.      32100000        29800000   -0.74
2   GOOGL                Alphabet Inc.      24700000        26500000    2.15
3    AMZN              Amazon.com Inc.      41300000        45200000    0.63
4    TSLA                   Tesla Inc.            22        78200000   -1.47
5    NVDA                 NVIDIA Corp.            22       158000000    3.28
6    META          Meta Platforms Inc.            22        21400000    1.12
7    NFLX                 Netflix Inc.            22        10100000   -0.56
8    ORCL                 Oracle Corp.            22        16200000    0.91
9     IBM                    IBM Corp.            22         7200000   -0.32
10   INTC                  Intel Corp.            22        48700000    1.45
11    AMD  Advanced Micro Devices Inc.            22        42100000    2.07
12   CSCO           Cisco Systems Inc.      22100000        23900000   -0.68
13   ADBE                   Adobe Inc.       7300000         8100000    1.36

In [ ]:
var.replace("[A-Za-z]","python",regex=True)

,Symbol,Security,Today-Volume,Average-Volume,Change
0,pythonpythonpythonpython,pythonpythonpythonpythonpython pythonpythonpyt...,58200000,61500000,1.82
1,pythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpyth...,32100000,29800000,-0.74
2,pythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpyth...,24700000,26500000,2.15
3,pythonpythonpythonpython,pythonpythonpythonpythonpythonpython.pythonpyt...,41300000,45200000,0.63
4,pythonpythonpythonpython,pythonpythonpythonpythonpython pythonpythonpyt...,1,78200000,-1.47
5,pythonpythonpythonpython,pythonpythonpythonpythonpythonpython pythonpyt...,1,158000000,3.28
6,pythonpythonpythonpython,pythonpythonpythonpython pythonpythonpythonpyt...,1,21400000,1.12
7,pythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpython pyt...,1,10100000,-0.56
8,pythonpythonpythonpython,pythonpythonpythonpythonpythonpython pythonpyt...,1,16200000,0.91
9,pythonpythonpython,pythonpythonpython pythonpythonpythonpython.,1,7200000,-0.32
10,pythonpythonpythonpython,pythonpythonpythonpythonpython pythonpythonpyt...,1,48700000,1.45
11,pythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpyth...,1,42100000,2.07
12,pythonpythonpythonpython,pythonpythonpythonpythonpython pythonpythonpyt...,22100000,23900000,-0.68
13,pythonpythonpythonpython,pythonpythonpythonpythonpython pythonpythonpyt...,7300000,8100000,1.36

In [ ]:
var.replace("[A-Za-z]","priyanka",regex=True)

,Symbol,Security,Today-Volume,Average-Volume,Change
0,priyankapriyankapriyankapriyanka,priyankapriyankapriyankapriyankapriyanka priya...,58200000,61500000,1.82
1,priyankapriyankapriyankapriyanka,priyankapriyankapriyankapriyankapriyankapriyan...,32100000,29800000,-0.74
2,priyankapriyankapriyankapriyankapriyanka,priyankapriyankapriyankapriyankapriyankapriyan...,24700000,26500000,2.15
3,priyankapriyankapriyankapriyanka,priyankapriyankapriyankapriyankapriyankapriyan...,41300000,45200000,0.63
4,priyankapriyankapriyankapriyanka,priyankapriyankapriyankapriyankapriyanka priya...,1,78200000,-1.47
5,priyankapriyankapriyankapriyanka,priyankapriyankapriyankapriyankapriyankapriyan...,1,158000000,3.28
6,priyankapriyankapriyankapriyanka,priyankapriyankapriyankapriyanka priyankapriya...,1,21400000,1.12
7,priyankapriyankapriyankapriyanka,priyankapriyankapriyankapriyankapriyankapriyan...,1,10100000,-0.56
8,priyankapriyankapriyankapriyanka,priyankapriyankapriyankapriyankapriyankapriyan...,1,16200000,0.91
9,priyankapriyankapriyanka,priyankapriyankapriyanka priyankapriyankapriya...,1,7200000,-0.32
10,priyankapriyankapriyankapriyanka,priyankapriyankapriyankapriyankapriyanka priya...,1,48700000,1.45
11,priyankapriyankapriyanka,priyankapriyankapriyankapriyankapriyankapriyan...,1,42100000,2.07
12,priyankapriyankapriyankapriyanka,priyankapriyankapriyankapriyankapriyanka priya...,22100000,23900000,-0.68
13,priyankapriyankapriyankapriyanka,priyankapriyankapriyankapriyankapriyanka priya...,7300000,8100000,1.36

In [ ]:
var.replace("[A-Za]","python",regex=True)

,Symbol,Security,Today-Volume,Average-Volume,Change
0,pythonpythonpythonpython,pythonpple pythonnc.,58200000,61500000,1.82
1,pythonpythonpythonpython,pythonicrosoft pythonorp.,32100000,29800000,-0.74
2,pythonpythonpythonpythonpython,pythonlphpythonbet pythonnc.,24700000,26500000,2.15
3,pythonpythonpythonpython,pythonmpythonzon.com pythonnc.,41300000,45200000,0.63
4,pythonpythonpythonpython,pythoneslpython pythonnc.,1,78200000,-1.47
5,pythonpythonpythonpython,pythonpythonpythonpythonpythonpython pythonorp.,1,158000000,3.28
6,pythonpythonpythonpython,pythonetpython pythonlpythontforms pythonnc.,1,21400000,1.12
7,pythonpythonpythonpython,pythonetflix pythonnc.,1,10100000,-0.56
8,pythonpythonpythonpython,pythonrpythoncle pythonorp.,1,16200000,0.91
9,pythonpythonpython,pythonpythonpython pythonorp.,1,7200000,-0.32
10,pythonpythonpythonpython,pythonntel pythonorp.,1,48700000,1.45
11,pythonpythonpython,pythondvpythonnced pythonicro pythonevices pyt...,1,42100000,2.07
12,pythonpythonpythonpython,pythonisco pythonystems pythonnc.,22100000,23900000,-0.68
13,pythonpythonpythonpython,pythondobe pythonnc.,7300000,8100000,1.36

In [ ]:
var.replace({"Symbol":'[A-Z]'},22,regex=True)

/tmp/ipykernel_2491/110037549.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  var.replace({"Symbol":'[A-Z]'},22,regex=True)

    Symbol                     Security  Today-Volume  Average-Volume  Change
0       22                   Apple Inc.      58200000        61500000    1.82
1       22              Microsoft Corp.      32100000        29800000   -0.74
2       22                Alphabet Inc.      24700000        26500000    2.15
3       22              Amazon.com Inc.      41300000        45200000    0.63
4       22                   Tesla Inc.             1        78200000   -1.47
5       22                 NVIDIA Corp.             1       158000000    3.28
6       22          Meta Platforms Inc.             1        21400000    1.12
7       22                 Netflix Inc.             1        10100000   -0.56
8       22                 Oracle Corp.             1        16200000    0.91
9       22                    IBM Corp.             1         7200000   -0.32
10      22                  Intel Corp.             1        48700000    1.45
11      22  Advanced Micro Devices Inc.             1        42100000    2.07
12      22           Cisco Systems Inc.      22100000        23900000   -0.68
13      22                   Adobe Inc.       7300000         8100000    1.36

In [ ]:
var.replace(1,method="ffill")          #forword

/tmp/ipykernel_2491/4173063640.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  var.replace(1,method="ffill")

   Symbol                     Security  Today-Volume  Average-Volume  Change
0    AAPL                   Apple Inc.      58200000        61500000    1.82
1    MSFT              Microsoft Corp.      32100000        29800000   -0.74
2   GOOGL                Alphabet Inc.      24700000        26500000    2.15
3    AMZN              Amazon.com Inc.      41300000        45200000    0.63
4    TSLA                   Tesla Inc.      41300000        78200000   -1.47
5    NVDA                 NVIDIA Corp.      41300000       158000000    3.28
6    META          Meta Platforms Inc.      41300000        21400000    1.12
7    NFLX                 Netflix Inc.      41300000        10100000   -0.56
8    ORCL                 Oracle Corp.      41300000        16200000    0.91
9     IBM                    IBM Corp.      41300000         7200000   -0.32
10   INTC                  Intel Corp.      41300000        48700000    1.45
11    AMD  Advanced Micro Devices Inc.      41300000        42100000    2.07
12   CSCO           Cisco Systems Inc.      22100000        23900000   -0.68
13   ADBE                   Adobe Inc.       7300000         8100000    1.36

In [ ]:
var.replace(1,method="bfill")          #backword

/tmp/ipykernel_2491/2799841267.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  var.replace(1,method="bfill")          #backword

   Symbol                     Security  Today-Volume  Average-Volume  Change
0    AAPL                   Apple Inc.      58200000        61500000    1.82
1    MSFT              Microsoft Corp.      32100000        29800000   -0.74
2   GOOGL                Alphabet Inc.      24700000        26500000    2.15
3    AMZN              Amazon.com Inc.      41300000        45200000    0.63
4    TSLA                   Tesla Inc.      22100000        78200000   -1.47
5    NVDA                 NVIDIA Corp.      22100000       158000000    3.28
6    META          Meta Platforms Inc.      22100000        21400000    1.12
7    NFLX                 Netflix Inc.      22100000        10100000   -0.56
8    ORCL                 Oracle Corp.      22100000        16200000    0.91
9     IBM                    IBM Corp.      22100000         7200000   -0.32
10   INTC                  Intel Corp.      22100000        48700000    1.45
11    AMD  Advanced Micro Devices Inc.      22100000        42100000    2.07
12   CSCO           Cisco Systems Inc.      22100000        23900000   -0.68
13   ADBE                   Adobe Inc.       7300000         8100000    1.36

In [ ]:
var.replace(1,method="ffill",limit=2)

/tmp/ipykernel_2491/1058011697.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  var.replace(1,method="ffill",limit=2)

   Symbol                     Security  Today-Volume  Average-Volume  Change
0    AAPL                   Apple Inc.      58200000        61500000    1.82
1    MSFT              Microsoft Corp.      32100000        29800000   -0.74
2   GOOGL                Alphabet Inc.      24700000        26500000    2.15
3    AMZN              Amazon.com Inc.      41300000        45200000    0.63
4    TSLA                   Tesla Inc.      41300000        78200000   -1.47
5    NVDA                 NVIDIA Corp.      41300000       158000000    3.28
6    META          Meta Platforms Inc.             1        21400000    1.12
7    NFLX                 Netflix Inc.             1        10100000   -0.56
8    ORCL                 Oracle Corp.             1        16200000    0.91
9     IBM                    IBM Corp.             1         7200000   -0.32
10   INTC                  Intel Corp.             1        48700000    1.45
11    AMD  Advanced Micro Devices Inc.             1        42100000    2.07
12   CSCO           Cisco Systems Inc.      22100000        23900000   -0.68
13   ADBE                   Adobe Inc.       7300000         8100000    1.36

In [ ]:
var.replace(1,method="ffill",limit=4)

/tmp/ipykernel_2491/465076494.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  var.replace(1,method="ffill",limit=4)

   Symbol                     Security  Today-Volume  Average-Volume  Change
0    AAPL                   Apple Inc.      58200000        61500000    1.82
1    MSFT              Microsoft Corp.      32100000        29800000   -0.74
2   GOOGL                Alphabet Inc.      24700000        26500000    2.15
3    AMZN              Amazon.com Inc.      41300000        45200000    0.63
4    TSLA                   Tesla Inc.      41300000        78200000   -1.47
5    NVDA                 NVIDIA Corp.      41300000       158000000    3.28
6    META          Meta Platforms Inc.      41300000        21400000    1.12
7    NFLX                 Netflix Inc.      41300000        10100000   -0.56
8    ORCL                 Oracle Corp.             1        16200000    0.91
9     IBM                    IBM Corp.             1         7200000   -0.32
10   INTC                  Intel Corp.             1        48700000    1.45
11    AMD  Advanced Micro Devices Inc.             1        42100000    2.07
12   CSCO           Cisco Systems Inc.      22100000        23900000   -0.68
13   ADBE                   Adobe Inc.       7300000         8100000    1.36

In [ ]:
var.replace(1,method="ffill",limit=3,inplace=True)

var

/tmp/ipykernel_2491/178192739.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  var.replace(1,method="ffill",limit=3,inplace=True)

   Symbol                     Security  Today-Volume  Average-Volume  Change
0    AAPL                   Apple Inc.      58200000        61500000    1.82
1    MSFT              Microsoft Corp.      32100000        29800000   -0.74
2   GOOGL                Alphabet Inc.      24700000        26500000    2.15
3    AMZN              Amazon.com Inc.      41300000        45200000    0.63
4    TSLA                   Tesla Inc.      41300000        78200000   -1.47
5    NVDA                 NVIDIA Corp.      41300000       158000000    3.28
6    META          Meta Platforms Inc.      41300000        21400000    1.12
7    NFLX                 Netflix Inc.             1        10100000   -0.56
8    ORCL                 Oracle Corp.             1        16200000    0.91
9     IBM                    IBM Corp.             1         7200000   -0.32
10   INTC                  Intel Corp.             1        48700000    1.45
11    AMD  Advanced Micro Devices Inc.             1        42100000    2.07
12   CSCO           Cisco Systems Inc.      22100000        23900000   -0.68
13   ADBE                   Adobe Inc.       7300000         8100000    1.36

In [ ]:
var

   Symbol                     Security  Today-Volume  Average-Volume  Change
0    AAPL                   Apple Inc.      58200000        61500000    1.82
1    MSFT              Microsoft Corp.      32100000        29800000   -0.74
2   GOOGL                Alphabet Inc.      24700000        26500000    2.15
3    AMZN              Amazon.com Inc.      41300000        45200000    0.63
4    TSLA                   Tesla Inc.      41300000        78200000   -1.47
5    NVDA                 NVIDIA Corp.      41300000       158000000    3.28
6    META          Meta Platforms Inc.      41300000        21400000    1.12
7    NFLX                 Netflix Inc.             1        10100000   -0.56
8    ORCL                 Oracle Corp.             1        16200000    0.91
9     IBM                    IBM Corp.             1         7200000   -0.32
10   INTC                  Intel Corp.             1        48700000    1.45
11    AMD  Advanced Micro Devices Inc.             1        42100000    2.07
12   CSCO           Cisco Systems Inc.      22100000        23900000   -0.68
13   ADBE                   Adobe Inc.       7300000         8100000    1.36

In [ ]:
# Interpolate

In [ ]:
import pandas as pd

var = pd.read_csv("/content/stock_volume_14.csv")

var

   Symbol                     Security  Today-Volume  Average-Volume  Change
0    AAPL                   Apple Inc.    58200000.0      61500000.0    1.82
1    MSFT              Microsoft Corp.    32100000.0      29800000.0   -0.74
2   GOOGL                Alphabet Inc.    24700000.0      26500000.0    2.15
3    AMZN              Amazon.com Inc.    41300000.0             NaN    0.63
4    TSLA                   Tesla Inc.           NaN      78200000.0   -1.47
5    NVDA                 NVIDIA Corp.           NaN     158000000.0    3.28
6    META          Meta Platforms Inc.           NaN             NaN    1.12
7    NFLX                 Netflix Inc.           NaN      10100000.0   -0.56
8    ORCL                 Oracle Corp.           NaN      16200000.0    0.91
9     IBM                    IBM Corp.           NaN       7200000.0   -0.32
10   INTC                  Intel Corp.           NaN      48700000.0    1.45
11    AMD  Advanced Micro Devices Inc.           NaN      42100000.0    2.07
12   CSCO           Cisco Systems Inc.    22100000.0      23900000.0   -0.68
13   ADBE                   Adobe Inc.     7300000.0       8100000.0    1.36

In [ ]:
var.interpolate()

/tmp/ipykernel_2491/1566664964.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  var.interpolate()

   Symbol                     Security  Today-Volume  Average-Volume  Change
0    AAPL                   Apple Inc.  5.820000e+07      61500000.0    1.82
1    MSFT              Microsoft Corp.  3.210000e+07      29800000.0   -0.74
2   GOOGL                Alphabet Inc.  2.470000e+07      26500000.0    2.15
3    AMZN              Amazon.com Inc.  4.130000e+07      52350000.0    0.63
4    TSLA                   Tesla Inc.  3.916667e+07      78200000.0   -1.47
5    NVDA                 NVIDIA Corp.  3.703333e+07     158000000.0    3.28
6    META          Meta Platforms Inc.  3.490000e+07      84050000.0    1.12
7    NFLX                 Netflix Inc.  3.276667e+07      10100000.0   -0.56
8    ORCL                 Oracle Corp.  3.063333e+07      16200000.0    0.91
9     IBM                    IBM Corp.  2.850000e+07       7200000.0   -0.32
10   INTC                  Intel Corp.  2.636667e+07      48700000.0    1.45
11    AMD  Advanced Micro Devices Inc.  2.423333e+07      42100000.0    2.07
12   CSCO           Cisco Systems Inc.  2.210000e+07      23900000.0   -0.68
13   ADBE                   Adobe Inc.  7.300000e+06       8100000.0    1.36

In [ ]:
var.interpolate(method="linear",axis=0)

/tmp/ipykernel_2491/3195347084.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  var.interpolate(method="linear",axis=0)

   Symbol                     Security  Today-Volume  Average-Volume  Change
0    AAPL                   Apple Inc.  5.820000e+07      61500000.0    1.82
1    MSFT              Microsoft Corp.  3.210000e+07      29800000.0   -0.74
2   GOOGL                Alphabet Inc.  2.470000e+07      26500000.0    2.15
3    AMZN              Amazon.com Inc.  4.130000e+07      52350000.0    0.63
4    TSLA                   Tesla Inc.  3.916667e+07      78200000.0   -1.47
5    NVDA                 NVIDIA Corp.  3.703333e+07     158000000.0    3.28
6    META          Meta Platforms Inc.  3.490000e+07      84050000.0    1.12
7    NFLX                 Netflix Inc.  3.276667e+07      10100000.0   -0.56
8    ORCL                 Oracle Corp.  3.063333e+07      16200000.0    0.91
9     IBM                    IBM Corp.  2.850000e+07       7200000.0   -0.32
10   INTC                  Intel Corp.  2.636667e+07      48700000.0    1.45
11    AMD  Advanced Micro Devices Inc.  2.423333e+07      42100000.0    2.07
12   CSCO           Cisco Systems Inc.  2.210000e+07      23900000.0   -0.68
13   ADBE                   Adobe Inc.  7.300000e+06       8100000.0    1.36

In [ ]:
var.interpolate(limit=2)

/tmp/ipykernel_2491/545238221.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  var.interpolate(limit=2)

   Symbol                     Security  Today-Volume  Average-Volume  Change
0    AAPL                   Apple Inc.  5.820000e+07      61500000.0    1.82
1    MSFT              Microsoft Corp.  3.210000e+07      29800000.0   -0.74
2   GOOGL                Alphabet Inc.  2.470000e+07      26500000.0    2.15
3    AMZN              Amazon.com Inc.  4.130000e+07      52350000.0    0.63
4    TSLA                   Tesla Inc.  3.916667e+07      78200000.0   -1.47
5    NVDA                 NVIDIA Corp.  3.703333e+07     158000000.0    3.28
6    META          Meta Platforms Inc.           NaN      84050000.0    1.12
7    NFLX                 Netflix Inc.           NaN      10100000.0   -0.56
8    ORCL                 Oracle Corp.           NaN      16200000.0    0.91
9     IBM                    IBM Corp.           NaN       7200000.0   -0.32
10   INTC                  Intel Corp.           NaN      48700000.0    1.45
11    AMD  Advanced Micro Devices Inc.           NaN      42100000.0    2.07
12   CSCO           Cisco Systems Inc.  2.210000e+07      23900000.0   -0.68
13   ADBE                   Adobe Inc.  7.300000e+06       8100000.0    1.36

In [ ]:
var.interpolate(limit_direction="forward",limit=2)

/tmp/ipykernel_2491/985317805.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  var.interpolate(limit_direction="forward",limit=2)

   Symbol                     Security  Today-Volume  Average-Volume  Change
0    AAPL                   Apple Inc.  5.820000e+07      61500000.0    1.82
1    MSFT              Microsoft Corp.  3.210000e+07      29800000.0   -0.74
2   GOOGL                Alphabet Inc.  2.470000e+07      26500000.0    2.15
3    AMZN              Amazon.com Inc.  4.130000e+07      52350000.0    0.63
4    TSLA                   Tesla Inc.  3.916667e+07      78200000.0   -1.47
5    NVDA                 NVIDIA Corp.  3.703333e+07     158000000.0    3.28
6    META          Meta Platforms Inc.           NaN      84050000.0    1.12
7    NFLX                 Netflix Inc.           NaN      10100000.0   -0.56
8    ORCL                 Oracle Corp.           NaN      16200000.0    0.91
9     IBM                    IBM Corp.           NaN       7200000.0   -0.32
10   INTC                  Intel Corp.           NaN      48700000.0    1.45
11    AMD  Advanced Micro Devices Inc.           NaN      42100000.0    2.07
12   CSCO           Cisco Systems Inc.  2.210000e+07      23900000.0   -0.68
13   ADBE                   Adobe Inc.  7.300000e+06       8100000.0    1.36

In [ ]:
var.interpolate(limit_direction="Backward",limit=2)

/tmp/ipykernel_2491/2069333013.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  var.interpolate(limit_direction="Backward",limit=2)

   Symbol                     Security  Today-Volume  Average-Volume  Change
0    AAPL                   Apple Inc.  5.820000e+07      61500000.0    1.82
1    MSFT              Microsoft Corp.  3.210000e+07      29800000.0   -0.74
2   GOOGL                Alphabet Inc.  2.470000e+07      26500000.0    2.15
3    AMZN              Amazon.com Inc.  4.130000e+07      52350000.0    0.63
4    TSLA                   Tesla Inc.           NaN      78200000.0   -1.47
5    NVDA                 NVIDIA Corp.           NaN     158000000.0    3.28
6    META          Meta Platforms Inc.           NaN      84050000.0    1.12
7    NFLX                 Netflix Inc.           NaN      10100000.0   -0.56
8    ORCL                 Oracle Corp.           NaN      16200000.0    0.91
9     IBM                    IBM Corp.           NaN       7200000.0   -0.32
10   INTC                  Intel Corp.  2.636667e+07      48700000.0    1.45
11    AMD  Advanced Micro Devices Inc.  2.423333e+07      42100000.0    2.07
12   CSCO           Cisco Systems Inc.  2.210000e+07      23900000.0   -0.68
13   ADBE                   Adobe Inc.  7.300000e+06       8100000.0    1.36

In [ ]:
var.interpolate(limit_direction="both",limit=2)

/tmp/ipykernel_2491/3871155077.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  var.interpolate(limit_direction="both",limit=2)

   Symbol                     Security  Today-Volume  Average-Volume  Change
0    AAPL                   Apple Inc.  5.820000e+07      61500000.0    1.82
1    MSFT              Microsoft Corp.  3.210000e+07      29800000.0   -0.74
2   GOOGL                Alphabet Inc.  2.470000e+07      26500000.0    2.15
3    AMZN              Amazon.com Inc.  4.130000e+07      52350000.0    0.63
4    TSLA                   Tesla Inc.  3.916667e+07      78200000.0   -1.47
5    NVDA                 NVIDIA Corp.  3.703333e+07     158000000.0    3.28
6    META          Meta Platforms Inc.           NaN      84050000.0    1.12
7    NFLX                 Netflix Inc.           NaN      10100000.0   -0.56
8    ORCL                 Oracle Corp.           NaN      16200000.0    0.91
9     IBM                    IBM Corp.           NaN       7200000.0   -0.32
10   INTC                  Intel Corp.  2.636667e+07      48700000.0    1.45
11    AMD  Advanced Micro Devices Inc.  2.423333e+07      42100000.0    2.07
12   CSCO           Cisco Systems Inc.  2.210000e+07      23900000.0   -0.68
13   ADBE                   Adobe Inc.  7.300000e+06       8100000.0    1.36

In [ ]:
var.interpolate(limit_area="inside")

/tmp/ipykernel_2491/996392095.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  var.interpolate(limit_area="inside")

   Symbol                     Security  Today-Volume  Average-Volume  Change
0    AAPL                   Apple Inc.  5.820000e+07      61500000.0    1.82
1    MSFT              Microsoft Corp.  3.210000e+07      29800000.0   -0.74
2   GOOGL                Alphabet Inc.  2.470000e+07      26500000.0    2.15
3    AMZN              Amazon.com Inc.  4.130000e+07      52350000.0    0.63
4    TSLA                   Tesla Inc.  3.916667e+07      78200000.0   -1.47
5    NVDA                 NVIDIA Corp.  3.703333e+07     158000000.0    3.28
6    META          Meta Platforms Inc.  3.490000e+07      84050000.0    1.12
7    NFLX                 Netflix Inc.  3.276667e+07      10100000.0   -0.56
8    ORCL                 Oracle Corp.  3.063333e+07      16200000.0    0.91
9     IBM                    IBM Corp.  2.850000e+07       7200000.0   -0.32
10   INTC                  Intel Corp.  2.636667e+07      48700000.0    1.45
11    AMD  Advanced Micro Devices Inc.  2.423333e+07      42100000.0    2.07
12   CSCO           Cisco Systems Inc.  2.210000e+07      23900000.0   -0.68
13   ADBE                   Adobe Inc.  7.300000e+06       8100000.0    1.36

In [ ]:
var.interpolate(limit_area="outside")

/tmp/ipykernel_2491/376205930.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  var.interpolate(limit_area="outside")

   Symbol                     Security  Today-Volume  Average-Volume  Change
0    AAPL                   Apple Inc.    58200000.0      61500000.0    1.82
1    MSFT              Microsoft Corp.    32100000.0      29800000.0   -0.74
2   GOOGL                Alphabet Inc.    24700000.0      26500000.0    2.15
3    AMZN              Amazon.com Inc.    41300000.0             NaN    0.63
4    TSLA                   Tesla Inc.           NaN      78200000.0   -1.47
5    NVDA                 NVIDIA Corp.           NaN     158000000.0    3.28
6    META          Meta Platforms Inc.           NaN             NaN    1.12
7    NFLX                 Netflix Inc.           NaN      10100000.0   -0.56
8    ORCL                 Oracle Corp.           NaN      16200000.0    0.91
9     IBM                    IBM Corp.           NaN       7200000.0   -0.32
10   INTC                  Intel Corp.           NaN      48700000.0    1.45
11    AMD  Advanced Micro Devices Inc.           NaN      42100000.0    2.07
12   CSCO           Cisco Systems Inc.    22100000.0      23900000.0   -0.68
13   ADBE                   Adobe Inc.     7300000.0       8100000.0    1.36

In [ ]:
import pandas as pd

var = pd.read_csv("/content/stock_volume_14.csv")

var

var.interpolate(limit_direction="both",limit=2,inplace=True)
var

/tmp/ipykernel_2491/3612820141.py:7: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  var.interpolate(limit_direction="both",limit=2,inplace=True)

   Symbol                     Security  Today-Volume  Average-Volume  Change
0    AAPL                   Apple Inc.  5.820000e+07      61500000.0    1.82
1    MSFT              Microsoft Corp.  3.210000e+07      29800000.0   -0.74
2   GOOGL                Alphabet Inc.  2.470000e+07      26500000.0    2.15
3    AMZN              Amazon.com Inc.  4.130000e+07      52350000.0    0.63
4    TSLA                   Tesla Inc.  3.916667e+07      78200000.0   -1.47
5    NVDA                 NVIDIA Corp.  3.703333e+07     158000000.0    3.28
6    META          Meta Platforms Inc.           NaN      84050000.0    1.12
7    NFLX                 Netflix Inc.           NaN      10100000.0   -0.56
8    ORCL                 Oracle Corp.           NaN      16200000.0    0.91
9     IBM                    IBM Corp.           NaN       7200000.0   -0.32
10   INTC                  Intel Corp.  2.636667e+07      48700000.0    1.45
11    AMD  Advanced Micro Devices Inc.  2.423333e+07      42100000.0    2.07
12   CSCO           Cisco Systems Inc.  2.210000e+07      23900000.0   -0.68
13   ADBE                   Adobe Inc.  7.300000e+06       8100000.0    1.36